/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

/**
 *
 * @author mr932
 */
public class DiemChiTietHocSinhGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form DiemChiTietHocSinhGUI
     */
    public DiemChiTietHocSinhGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        scrollPaneDiemTbMonTungHocSinh = new javax.swing.JScrollPane();
        tbDiemTbMonTungHocSinh = new javax.swing.JTable();
        panelInput = new javax.swing.JPanel();
        lbLop = new javax.swing.JLabel();
        lbNamHoc = new javax.swing.JLabel();
        lbLop1 = new javax.swing.JLabel();
        lbLop2 = new javax.swing.JLabel();
        lbLop3 = new javax.swing.JLabel();
        lbNamHoc2 = new javax.swing.JLabel();
        lbLop4 = new javax.swing.JLabel();
        lbNamHoc3 = new javax.swing.JLabel();
        lbLop5 = new javax.swing.JLabel();
        lbNamHoc4 = new javax.swing.JLabel();
        lbLop6 = new javax.swing.JLabel();
        lbNamHoc5 = new javax.swing.JLabel();
        lbLop7 = new javax.swing.JLabel();
        lbNamHoc6 = new javax.swing.JLabel();
        lbLop8 = new javax.swing.JLabel();
        lbNamHoc7 = new javax.swing.JLabel();
        lbLop9 = new javax.swing.JLabel();
        lbLop10 = new javax.swing.JLabel();
        lbNamHoc10 = new javax.swing.JLabel();
        lbNamHoc11 = new javax.swing.JLabel();
        lbNamHoc8 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        scrollPaneDiemTbMonTungHocSinh.setToolTipText("");
        scrollPaneDiemTbMonTungHocSinh.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDiemTbMonTungHocSinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDiemTbMonTungHocSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên môn", "Điểm 15 phút", "Điểm 1 tiết", "Điểm thi học kỳ", "Điểm TB học kì"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDiemTbMonTungHocSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemTbMonTungHocSinhtbDSDSmouseClick(evt);
            }
        });
        scrollPaneDiemTbMonTungHocSinh.setViewportView(tbDiemTbMonTungHocSinh);

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        lbLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop.setForeground(new java.awt.Color(23, 35, 51));
        lbLop.setText("Mã");

        lbNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc.setText("thông tin");
        lbNamHoc.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop1.setForeground(new java.awt.Color(23, 35, 51));
        lbLop1.setText("Thông tin học sinh");

        lbLop2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop2.setForeground(new java.awt.Color(23, 35, 51));
        lbLop2.setText("Lớp");

        lbLop3.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop3.setForeground(new java.awt.Color(23, 35, 51));
        lbLop3.setText("Học kỳ");

        lbNamHoc2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc2.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc2.setText("thông tin");
        lbNamHoc2.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop4.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop4.setForeground(new java.awt.Color(23, 35, 51));
        lbLop4.setText("Điểm trung bình");

        lbNamHoc3.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc3.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc3.setText("thông tin");
        lbNamHoc3.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop5.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop5.setForeground(new java.awt.Color(23, 35, 51));
        lbLop5.setText("Họ và tên");

        lbNamHoc4.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc4.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc4.setText("thông tin");
        lbNamHoc4.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop6.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop6.setForeground(new java.awt.Color(23, 35, 51));
        lbLop6.setText("GVCN");

        lbNamHoc5.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc5.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc5.setText("thông tin");
        lbNamHoc5.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop7.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop7.setForeground(new java.awt.Color(23, 35, 51));
        lbLop7.setText("Năm học");

        lbNamHoc6.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc6.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc6.setText("thông tin");
        lbNamHoc6.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop8.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop8.setForeground(new java.awt.Color(23, 35, 51));
        lbLop8.setText("Hạnh kiểm");

        lbNamHoc7.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc7.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc7.setText("thông tin");
        lbNamHoc7.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop9.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop9.setForeground(new java.awt.Color(23, 35, 51));
        lbLop9.setText("Xếp loại");

        lbLop10.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop10.setForeground(new java.awt.Color(23, 35, 51));
        lbLop10.setText("Hạng");

        lbNamHoc10.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc10.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc10.setText("thông tin");
        lbNamHoc10.setPreferredSize(new java.awt.Dimension(115, 13));

        lbNamHoc11.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc11.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc11.setText("thông tin");
        lbNamHoc11.setPreferredSize(new java.awt.Dimension(115, 13));

        lbNamHoc8.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc8.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc8.setText("thông tin");
        lbNamHoc8.setPreferredSize(new java.awt.Dimension(115, 13));

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLop2)
                            .addComponent(lbLop4)
                            .addComponent(lbLop3)
                            .addComponent(lbLop))
                        .addGap(34, 34, 34)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNamHoc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamHoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamHoc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLop8)
                            .addComponent(lbLop7)
                            .addComponent(lbLop5)
                            .addComponent(lbLop6))
                        .addGap(33, 33, 33)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbNamHoc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamHoc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamHoc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNamHoc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbLop1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLop9)
                    .addComponent(lbLop10))
                .addGap(18, 18, 18)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbNamHoc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamHoc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLop1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbLop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLop2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLop3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLop4))
                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addComponent(lbNamHoc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbNamHoc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbNamHoc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbNamHoc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbLop10)
                                .addComponent(lbNamHoc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbLop9)
                                .addComponent(lbNamHoc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbLop5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                                    .addComponent(lbNamHoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbNamHoc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbLop6)
                                        .addComponent(lbNamHoc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbLop7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbLop8))))))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        btnReport.setText("Report");

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel1.setText("Kết Quả Học Tập Học Kỳ");

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneDiemTbMonTungHocSinh))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport)
                .addGap(111, 111, 111))
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(scrollPaneDiemTbMonTungHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDiemTbMonTungHocSinhtbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemTbMonTungHocSinhtbDSDSmouseClick
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDiemTbMonTungHocSinhtbDSDSmouseClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbLop1;
    private javax.swing.JLabel lbLop10;
    private javax.swing.JLabel lbLop2;
    private javax.swing.JLabel lbLop3;
    private javax.swing.JLabel lbLop4;
    private javax.swing.JLabel lbLop5;
    private javax.swing.JLabel lbLop6;
    private javax.swing.JLabel lbLop7;
    private javax.swing.JLabel lbLop8;
    private javax.swing.JLabel lbLop9;
    private javax.swing.JLabel lbNamHoc;
    private javax.swing.JLabel lbNamHoc10;
    private javax.swing.JLabel lbNamHoc11;
    private javax.swing.JLabel lbNamHoc2;
    private javax.swing.JLabel lbNamHoc3;
    private javax.swing.JLabel lbNamHoc4;
    private javax.swing.JLabel lbNamHoc5;
    private javax.swing.JLabel lbNamHoc6;
    private javax.swing.JLabel lbNamHoc7;
    private javax.swing.JLabel lbNamHoc8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JScrollPane scrollPaneDiemTbMonTungHocSinh;
    private javax.swing.JTable tbDiemTbMonTungHocSinh;
    // End of variables declaration//GEN-END:variables
}
