/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

/**
 *
 * @author mr932
 */
public class LichGiangDayGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThoiKhoaBieuGUI
     */
    public LichGiangDayGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbMaGvQLDBM1 = new javax.swing.JLabel();
        lbMaGvQLDBM2 = new javax.swing.JLabel();
        functionPanel = new javax.swing.JPanel();
        scrollPaneDiemTbMonTungHocSinh = new javax.swing.JScrollPane();
        tbDiemTbMonTungHocSinh = new javax.swing.JTable();
        panelInput = new javax.swing.JPanel();
        lbHocKy = new javax.swing.JLabel();
        lbNamHoc = new javax.swing.JLabel();
        cbxNamHoc = new javax.swing.JComboBox<>();
        radHk1 = new javax.swing.JRadioButton();
        radHk2 = new javax.swing.JRadioButton();
        btnDocDanhSach = new javax.swing.JButton();
        txTimKiemTheoMa = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txTimKiemTheoHoTen = new javax.swing.JTextField();
        txTimKiemTheoDiem = new javax.swing.JTextField();
        txTimKiemTheoDiem1 = new javax.swing.JTextField();
        txTimKiemTheoDiem2 = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 35, 51));
        jLabel5.setText("Lịch Giảng Dạy");

        lbMaGvQLDBM1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMaGvQLDBM1.setForeground(new java.awt.Color(23, 35, 51));
        lbMaGvQLDBM1.setText("Tên giáo viên");

        lbMaGvQLDBM2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMaGvQLDBM2.setForeground(new java.awt.Color(23, 35, 51));
        lbMaGvQLDBM2.setText("Môn phụ trách");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaGvQLDBM2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMaGvQLDBM1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(63, 63, 63))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMaGvQLDBM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMaGvQLDBM2)
                .addGap(27, 27, 27))
        );

        scrollPaneDiemTbMonTungHocSinh.setToolTipText("");
        scrollPaneDiemTbMonTungHocSinh.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDiemTbMonTungHocSinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDiemTbMonTungHocSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Thứ", "Lớp", "Tiết bắt đầu", "Tiết kết thúc", "Số tiết"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDiemTbMonTungHocSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemTbMonTungHocSinhtbDSDSmouseClick(evt);
            }
        });
        scrollPaneDiemTbMonTungHocSinh.setViewportView(tbDiemTbMonTungHocSinh);

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        lbHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbHocKy.setText("Học kỳ");

        lbNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc.setText("Năm học");

        cbxNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        radHk1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk1.setText("1");
        radHk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHk1ActionPerformed(evt);
            }
        });

        radHk2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk2.setText("2");
        radHk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHk2ActionPerformed(evt);
            }
        });

        btnDocDanhSach.setBackground(new java.awt.Color(23, 35, 51));
        btnDocDanhSach.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDocDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDocDanhSach.setText("Đọc Danh Sách");

        txTimKiemTheoMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTimKiemTheoMa.setText("Tìm theo thứ ...");
        txTimKiemTheoMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txTimKiemTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTimKiemTheoMaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(23, 35, 51));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");

        txTimKiemTheoHoTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTimKiemTheoHoTen.setText("Tìm theo lớp ...");
        txTimKiemTheoHoTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        txTimKiemTheoDiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTimKiemTheoDiem.setText("Tìm theo tiết bd ...");
        txTimKiemTheoDiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        txTimKiemTheoDiem1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTimKiemTheoDiem1.setText("Tìm theo tiết kt ...");
        txTimKiemTheoDiem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        txTimKiemTheoDiem2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTimKiemTheoDiem2.setText("Tìm theo số tiết ...");
        txTimKiemTheoDiem2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txTimKiemTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txTimKiemTheoHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txTimKiemTheoDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txTimKiemTheoDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txTimKiemTheoDiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbNamHoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbHocKy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radHk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radHk2)
                .addGap(18, 18, 18)
                .addComponent(btnDocDanhSach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamHoc)
                    .addComponent(lbHocKy)
                    .addComponent(radHk1)
                    .addComponent(radHk2)
                    .addComponent(btnDocDanhSach))
                .addGap(41, 41, 41)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTimKiemTheoHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKiemTheoDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(txTimKiemTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKiemTheoDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKiemTheoDiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnReport.setText("Report");

        btnExport.setText("Export");

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneDiemTbMonTungHocSinh))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(113, 113, 113))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(scrollPaneDiemTbMonTungHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReport)
                    .addComponent(btnExport))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDiemTbMonTungHocSinhtbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemTbMonTungHocSinhtbDSDSmouseClick
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDiemTbMonTungHocSinhtbDSDSmouseClick

    private void radHk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHk1ActionPerformed

    private void radHk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHk2ActionPerformed

    private void txTimKiemTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTimKiemTheoMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTimKiemTheoMaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocDanhSach;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxNamHoc;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbHocKy;
    private javax.swing.JLabel lbMaGvQLDBM1;
    private javax.swing.JLabel lbMaGvQLDBM2;
    private javax.swing.JLabel lbNamHoc;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JRadioButton radHk1;
    private javax.swing.JRadioButton radHk2;
    private javax.swing.JScrollPane scrollPaneDiemTbMonTungHocSinh;
    private javax.swing.JTable tbDiemTbMonTungHocSinh;
    private javax.swing.JTextField txTimKiemTheoDiem;
    private javax.swing.JTextField txTimKiemTheoDiem1;
    private javax.swing.JTextField txTimKiemTheoDiem2;
    private javax.swing.JTextField txTimKiemTheoHoTen;
    private javax.swing.JTextField txTimKiemTheoMa;
    // End of variables declaration//GEN-END:variables
}
