/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.HocKyBUS;
import BusinessLogicLayer.NamHocBUS;
import BusinessLogicLayer.DiemBUS;
import BusinessLogicLayer.DiemHocKiBUS;
import BusinessLogicLayer.GiaoVienBUS;
import BusinessLogicLayer.HS_LopBUS;
import BusinessLogicLayer.HocBaCuoiNamBUS;
import BusinessLogicLayer.HocSinhBUS;
import BusinessLogicLayer.KetQuaHocTapHocKyBUS;
import BusinessLogicLayer.LoaiDiemBUS;
import BusinessLogicLayer.LopBUS;
import BusinessLogicLayer.MonHocBUS;
import BusinessLogicLayer.PhanCongCNBUS;
import BusinessLogicLayer.PhanCongGDBUS;
import BusinessLogicLayer.PhongBUS;
import BusinessLogicLayer.TKBBUS;
import java.awt.Button;
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author mr932
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private final static String HOC_KY_HIEN_TAI = "2";
    BaoTriGUI baoTriGUI;
    DangNhapGUI dangNhapGUI;
    QuanLyGiaoVienGUI giaoVienGUI;
    QuanLyDiemSoGUI diemSoGUI;
    QuanLyHocSinhGUI hocSinhGUI;
    QuanLyLopGUI lopGUI;
    QuanLyMonHocGUI monHocGUI;
    ThongKeGUI thongKeGUI;
    QuanLyChuNhiemGUI quanLyChuNhiemGUI;
    PhanCongGiangDayGUI phanCongGiangDayGUI;
    ThoiKhoaBieuGUI thoiKhoaBieuGUI;
    QuanLyDiemBoMonGUI quanLyDiemBoMonGUI;
    SubMenuDiem subMenuDiem;
    public MainFrame() throws Exception {
        initComponents();
        
        //Toolkit toolkit = Toolkit.getDefaultToolkit();
        //double width = toolkit.getScreenSize().getWidth();
        //double height = toolkit.getScreenSize().getHeight();
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();
        this.setSize((int)width, (int)height);
        taiDuLieu();
        giaoVienGUI = new QuanLyGiaoVienGUI();
        hocSinhGUI = new QuanLyHocSinhGUI();
        lopGUI = new QuanLyLopGUI();
        monHocGUI = new QuanLyMonHocGUI();
        phanCongGiangDayGUI = new PhanCongGiangDayGUI();
        thoiKhoaBieuGUI = new ThoiKhoaBieuGUI();
        quanLyDiemBoMonGUI = new QuanLyDiemBoMonGUI();
        diemSoGUI = new QuanLyDiemSoGUI();
        quanLyChuNhiemGUI = new QuanLyChuNhiemGUI();
        subMenuDiem = new SubMenuDiem(funPanel, diemSoGUI, quanLyDiemBoMonGUI, quanLyChuNhiemGUI);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funPanel = new javax.swing.JPanel();
        iconTruong = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        pnQLHS = new javax.swing.JPanel();
        inQLHS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnQLGV = new javax.swing.JPanel();
        inQLGV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnQLLH = new javax.swing.JPanel();
        inQLLH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnQLMH = new javax.swing.JPanel();
        inQLMH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnQLD = new javax.swing.JPanel();
        inQLD = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnPCGD = new javax.swing.JPanel();
        inPCGD = new javax.swing.JPanel();
        lbPCGD = new javax.swing.JLabel();
        pnTKB = new javax.swing.JPanel();
        inTKB = new javax.swing.JPanel();
        lbTKB = new javax.swing.JLabel();
        iconHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        funPanel.setBackground(new java.awt.Color(71, 120, 190));

        iconTruong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_Education-Filled_1_3672901.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Trường Trung Học Phổ Thông ABC");

        javax.swing.GroupLayout funPanelLayout = new javax.swing.GroupLayout(funPanel);
        funPanel.setLayout(funPanelLayout);
        funPanelLayout.setHorizontalGroup(
            funPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funPanelLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(funPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(iconTruong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(210, 210, 210))))
        );
        funPanelLayout.setVerticalGroup(
            funPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(iconTruong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(289, 289, 289))
        );

        sidePanel.setBackground(new java.awt.Color(23, 35, 51));

        pnQLHS.setBackground(new java.awt.Color(23, 35, 51));
        pnQLHS.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        pnQLHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnQLHSMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQLHS(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLHSMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnQLHSMouseEntered(evt);
            }
        });

        inQLHS.setOpaque(false);

        javax.swing.GroupLayout inQLHSLayout = new javax.swing.GroupLayout(inQLHS);
        inQLHS.setLayout(inQLHSLayout);
        inQLHSLayout.setHorizontalGroup(
            inQLHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        inQLHSLayout.setVerticalGroup(
            inQLHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản Lý Học Sinh");

        javax.swing.GroupLayout pnQLHSLayout = new javax.swing.GroupLayout(pnQLHS);
        pnQLHS.setLayout(pnQLHSLayout);
        pnQLHSLayout.setHorizontalGroup(
            pnQLHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLHSLayout.createSequentialGroup()
                .addComponent(inQLHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        pnQLHSLayout.setVerticalGroup(
            pnQLHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inQLHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnQLHSLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnQLGV.setBackground(new java.awt.Color(23, 35, 51));
        pnQLGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnQLGVMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLGVclick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLGVMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnQLGVMouseEntered(evt);
            }
        });

        inQLGV.setOpaque(false);

        javax.swing.GroupLayout inQLGVLayout = new javax.swing.GroupLayout(inQLGV);
        inQLGV.setLayout(inQLGVLayout);
        inQLGVLayout.setHorizontalGroup(
            inQLGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        inQLGVLayout.setVerticalGroup(
            inQLGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản Lý Giáo Viên");

        javax.swing.GroupLayout pnQLGVLayout = new javax.swing.GroupLayout(pnQLGV);
        pnQLGV.setLayout(pnQLGVLayout);
        pnQLGVLayout.setHorizontalGroup(
            pnQLGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLGVLayout.createSequentialGroup()
                .addComponent(inQLGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnQLGVLayout.setVerticalGroup(
            pnQLGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inQLGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnQLGVLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnQLLH.setBackground(new java.awt.Color(23, 35, 51));
        pnQLLH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnQLLHMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLLHclick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLLHMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnQLLHMouseEntered(evt);
            }
        });

        inQLLH.setOpaque(false);

        javax.swing.GroupLayout inQLLHLayout = new javax.swing.GroupLayout(inQLLH);
        inQLLH.setLayout(inQLLHLayout);
        inQLLHLayout.setHorizontalGroup(
            inQLLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        inQLLHLayout.setVerticalGroup(
            inQLLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quản Lý Lớp Học");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLLH(evt);
            }
        });

        javax.swing.GroupLayout pnQLLHLayout = new javax.swing.GroupLayout(pnQLLH);
        pnQLLH.setLayout(pnQLLHLayout);
        pnQLLHLayout.setHorizontalGroup(
            pnQLLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLLHLayout.createSequentialGroup()
                .addComponent(inQLLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnQLLHLayout.setVerticalGroup(
            pnQLLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inQLLH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnQLLHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnQLMH.setBackground(new java.awt.Color(23, 35, 51));
        pnQLMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnQLMHMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLMHclick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLMHMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnQLMHMouseEntered(evt);
            }
        });

        inQLMH.setOpaque(false);

        javax.swing.GroupLayout inQLMHLayout = new javax.swing.GroupLayout(inQLMH);
        inQLMH.setLayout(inQLMHLayout);
        inQLMHLayout.setHorizontalGroup(
            inQLMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        inQLMHLayout.setVerticalGroup(
            inQLMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quản Lý Môn Học");

        javax.swing.GroupLayout pnQLMHLayout = new javax.swing.GroupLayout(pnQLMH);
        pnQLMH.setLayout(pnQLMHLayout);
        pnQLMHLayout.setHorizontalGroup(
            pnQLMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLMHLayout.createSequentialGroup()
                .addComponent(inQLMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(100, 100, 100))
        );
        pnQLMHLayout.setVerticalGroup(
            pnQLMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inQLMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnQLMHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnQLD.setBackground(new java.awt.Color(23, 35, 51));
        pnQLD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnQLDMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLDclick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLDMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnQLDMouseEntered(evt);
            }
        });

        inQLD.setOpaque(false);

        javax.swing.GroupLayout inQLDLayout = new javax.swing.GroupLayout(inQLD);
        inQLD.setLayout(inQLDLayout);
        inQLDLayout.setHorizontalGroup(
            inQLDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        inQLDLayout.setVerticalGroup(
            inQLDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quản Lý Điểm");

        javax.swing.GroupLayout pnQLDLayout = new javax.swing.GroupLayout(pnQLD);
        pnQLD.setLayout(pnQLDLayout);
        pnQLDLayout.setHorizontalGroup(
            pnQLDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLDLayout.createSequentialGroup()
                .addComponent(inQLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnQLDLayout.setVerticalGroup(
            pnQLDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inQLD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnQLDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnPCGD.setBackground(new java.awt.Color(23, 35, 51));
        pnPCGD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnPCGDMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPCGDclick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnPCGDMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnPCGDMouseEntered(evt);
            }
        });

        inPCGD.setOpaque(false);

        javax.swing.GroupLayout inPCGDLayout = new javax.swing.GroupLayout(inPCGD);
        inPCGD.setLayout(inPCGDLayout);
        inPCGDLayout.setHorizontalGroup(
            inPCGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        inPCGDLayout.setVerticalGroup(
            inPCGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbPCGD.setBackground(new java.awt.Color(255, 255, 255));
        lbPCGD.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbPCGD.setForeground(new java.awt.Color(255, 255, 255));
        lbPCGD.setText("Phân Công Giảng Dạy");

        javax.swing.GroupLayout pnPCGDLayout = new javax.swing.GroupLayout(pnPCGD);
        pnPCGD.setLayout(pnPCGDLayout);
        pnPCGDLayout.setHorizontalGroup(
            pnPCGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPCGDLayout.createSequentialGroup()
                .addComponent(inPCGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(lbPCGD)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnPCGDLayout.setVerticalGroup(
            pnPCGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inPCGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnPCGDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbPCGD)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnTKB.setBackground(new java.awt.Color(23, 35, 51));
        pnTKB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTKBMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTKBclick(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnTKBMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnTKBMouseEntered(evt);
            }
        });

        inTKB.setOpaque(false);

        javax.swing.GroupLayout inTKBLayout = new javax.swing.GroupLayout(inTKB);
        inTKB.setLayout(inTKBLayout);
        inTKBLayout.setHorizontalGroup(
            inTKBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        inTKBLayout.setVerticalGroup(
            inTKBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbTKB.setBackground(new java.awt.Color(255, 255, 255));
        lbTKB.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbTKB.setForeground(new java.awt.Color(255, 255, 255));
        lbTKB.setText("Thời Khóa Biểu");

        javax.swing.GroupLayout pnTKBLayout = new javax.swing.GroupLayout(pnTKB);
        pnTKB.setLayout(pnTKBLayout);
        pnTKBLayout.setHorizontalGroup(
            pnTKBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTKBLayout.createSequentialGroup()
                .addComponent(inTKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(lbTKB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnTKBLayout.setVerticalGroup(
            pnTKBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inTKB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTKBLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTKB)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        iconHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_university_3992932.png"))); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(iconHeader))
                    .addComponent(pnQLD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTKB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnQLMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnQLLH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnQLGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnQLHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPCGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconHeader)
                .addGap(26, 26, 26)
                .addComponent(pnQLHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnQLGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnQLLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnQLMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnQLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnPCGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnTKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(funPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbQLHS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQLHS
        // TODO add your handling code here:
        //openPanel(hocSinhGUI);
    }//GEN-LAST:event_lbQLHS

    private void pnQLGVclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLGVclick
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnQLGVclick

    private void pnQLHSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLHSMousePressed
        // TODO add your handling code here:
        //openPanel(hocSinhGUI);
        openJInternalFrame(hocSinhGUI);
        setColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);
        resetColor(pnQLLH, inQLLH);
        resetColor(pnQLMH, inQLMH);
        resetColor(pnQLD, inQLD);
        resetColor(pnPCGD, inPCGD);
        resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnQLHSMousePressed

    private void pnQLGVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLGVMousePressed
        // TODO add your handling code here:
        openJInternalFrame(giaoVienGUI);
        setColor(pnQLGV, inQLGV);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLLH, inQLLH);
        resetColor(pnQLMH, inQLMH);
        resetColor(pnQLD, inQLD);
        resetColor(pnPCGD, inPCGD);
        resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnQLGVMousePressed

    private void pnQLLHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLLHMousePressed
        // TODO add your handling code here:
        openJInternalFrame(lopGUI);
        setColor(pnQLLH, inQLLH);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);

        resetColor(pnQLMH, inQLMH);
        resetColor(pnQLD, inQLD);
        resetColor(pnPCGD, inPCGD);
        resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnQLLHMousePressed

    private void pnQLMHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLMHMousePressed
        // TODO add your handling code here:
        //openPanel(monHocGUI);
        openJInternalFrame(monHocGUI);
        setColor(pnQLMH, inQLMH);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);
        resetColor(pnQLLH, inQLLH);

        resetColor(pnQLD, inQLD);
        resetColor(pnPCGD, inPCGD);
        resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnQLMHMousePressed

    private void pnQLDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDMousePressed
        // TODO add your handling code here:
        //openJInternalFrame(quanLyDiemBoMonGUI);
        if (subMenuDiem.isVisible())
            subMenuDiem.setVisible(false);
        else{
            openSubMenu(subMenuDiem);
        }
        
        setColor(pnQLD, inQLD);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);
        resetColor(pnQLLH, inQLLH);
        resetColor(pnQLMH, inQLMH);
        resetColor(pnPCGD, inPCGD);
        resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnQLDMousePressed

    private void pnPCGDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPCGDMousePressed
        // TODO add your handling code here:
        openJInternalFrame(phanCongGiangDayGUI);
        setColor(pnPCGD, inPCGD);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);
        resetColor(pnQLLH, inQLLH);
        resetColor(pnQLMH, inQLMH);
        resetColor(pnQLD, inQLD);
        resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnPCGDMousePressed

    private void pnTKBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTKBMousePressed
        // TODO add your handling code here:
        openJInternalFrame(thoiKhoaBieuGUI);
        setColor(pnTKB, inTKB);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);
        resetColor(pnQLLH, inQLLH);
        resetColor(pnQLMH, inQLMH);
        resetColor(pnQLD, inQLD);
        resetColor(pnPCGD, inPCGD);
    }//GEN-LAST:event_pnTKBMousePressed

    private void pnQLLH(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLLH
        // TODO add your handling code here:
        openJInternalFrame(lopGUI);
        setColor(pnQLLH, inQLLH);
        resetColor(pnQLHS, inQLHS);
        resetColor(pnQLGV, inQLGV);
        resetColor(pnTKB, inTKB);
        resetColor(pnQLMH, inQLMH);
        resetColor(pnQLD, inQLD);
        resetColor(pnPCGD, inPCGD);
    }//GEN-LAST:event_pnQLLH

    private void pnQLMHclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLMHclick
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnQLMHclick

    private void pnQLDclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDclick
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnQLDclick

    private void pnPCGDclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPCGDclick
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnPCGDclick

    private void pnTKBclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTKBclick
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnTKBclick

    private void pnQLLHclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLLHclick
        // TODO add your handling code here:

    }//GEN-LAST:event_pnQLLHclick

    private void pnQLGVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLGVMouseEntered
        // TODO add your handling code here:
        setColor(pnQLGV, inQLGV);
    }//GEN-LAST:event_pnQLGVMouseEntered

    private void pnQLGVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLGVMouseExited
        // TODO add your handling code here:
        if (!giaoVienGUI.isVisible())
            resetColor(pnQLGV, inQLGV);
    }//GEN-LAST:event_pnQLGVMouseExited

    private void pnQLHSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLHSMouseEntered
        // TODO add your handling code here:
        setColor(pnQLHS, inQLHS);
    }//GEN-LAST:event_pnQLHSMouseEntered

    private void pnQLHSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLHSMouseExited
        // TODO add your handling code here:
        if (!hocSinhGUI.isVisible())
            resetColor(pnQLHS, inQLHS);
    }//GEN-LAST:event_pnQLHSMouseExited

    private void pnQLLHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLLHMouseEntered
        // TODO add your handling code here:
        setColor(pnQLLH, inQLLH);
    }//GEN-LAST:event_pnQLLHMouseEntered

    private void pnQLLHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLLHMouseExited
        // TODO add your handling code here:
        if (!lopGUI.isVisible())
            resetColor(pnQLLH, inQLLH);
    }//GEN-LAST:event_pnQLLHMouseExited

    private void pnQLMHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLMHMouseEntered
        // TODO add your handling code here:
        setColor(pnQLMH, inQLMH);
    }//GEN-LAST:event_pnQLMHMouseEntered

    private void pnQLMHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLMHMouseExited
        // TODO add your handling code here:
        if (!monHocGUI.isVisible())
            resetColor(pnQLMH, inQLMH);
    }//GEN-LAST:event_pnQLMHMouseExited

    private void pnQLDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDMouseEntered
        // TODO add your handling code here:
        setColor(pnQLD, inQLD);
    }//GEN-LAST:event_pnQLDMouseEntered

    private void pnQLDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDMouseExited
        // TODO add your handling code here:
        if (!diemSoGUI.isVisible() && !quanLyChuNhiemGUI.isVisible() && !quanLyDiemBoMonGUI.isVisible() && !subMenuDiem.isVisible())
            resetColor(pnQLD, inQLD);
    }//GEN-LAST:event_pnQLDMouseExited

    private void pnPCGDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPCGDMouseEntered
        // TODO add your handling code here:
        setColor(pnPCGD, inPCGD);
    }//GEN-LAST:event_pnPCGDMouseEntered

    private void pnPCGDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPCGDMouseExited
        // TODO add your handling code here:
        if (!phanCongGiangDayGUI.isVisible())
            resetColor(pnPCGD, inPCGD);
    }//GEN-LAST:event_pnPCGDMouseExited

    private void pnTKBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTKBMouseEntered
        // TODO add your handling code here:
        setColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnTKBMouseEntered

    private void pnTKBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTKBMouseExited
        // TODO add your handling code here:
        if (!thoiKhoaBieuGUI.isVisible())
            resetColor(pnTKB, inTKB);
    }//GEN-LAST:event_pnTKBMouseExited
    
    private void setColor(JPanel pane, JPanel indicator) {
        pane.setBackground(new Color(41, 57, 80));
        indicator.setOpaque(true);
    }

    private void resetColor(JPanel pane, JPanel indicator) {
        pane.setBackground(new Color(23, 35, 51));
        indicator.setOpaque(false);
    }
    
    public void openJInternalFrame(JInternalFrame internalFrame){
        int height = funPanel.getHeight();
        int width = funPanel.getWidth();
        funPanel.removeAll();
        internalFrame.setSize(width, height);
        funPanel.add(internalFrame).setVisible(true);
        funPanel.repaint();
        funPanel.revalidate();
    }
    
    private void openSubMenu(JFrame frame){
        //frame = new JFrame();
        frame.setLocation(pnQLD.getX() + pnQLD.getWidth(), pnQLD.getY() + 45);
        frame.setSize(380, 195);
        frame.setVisible(true);
    }
    
    private void taiDuLieu() throws Exception{
        HocSinhBUS hsBus = new HocSinhBUS();
        hsBus.docDSHS();
        
        MonHocBUS mhBus = new MonHocBUS();
        mhBus.docDSMH();
        
        GiaoVienBUS gvBus = new GiaoVienBUS();
        gvBus.docDSGV(mhBus.getDsmh());
        
        LoaiDiemBUS loaiDiemBus = new LoaiDiemBUS();
        loaiDiemBus.docDSLD();
        
        NamHocBUS namHocBus = new NamHocBUS();
        namHocBus.doc();
        
        HocKyBUS hocKyBus = new HocKyBUS();
        hocKyBus.doc();
        
        DiemBUS diemBus = new DiemBUS();
        diemBus.docDSD(hsBus.getDshs(), mhBus.getDsmh(), hocKyBus.getDshk(), namHocBus.getDsnh(), loaiDiemBus.getDsld());
        
        PhongBUS phongBus = new PhongBUS();
        phongBus.doc();
        
        LopBUS lopBus = new LopBUS();
        lopBus.doc(namHocBus.getDsnh(), gvBus.getDsgv(), phongBus.getDsphong());
        
        HS_LopBUS hslopBus = new HS_LopBUS();
        hslopBus.doc(hsBus.getDshs(), lopBus.getDslop(), hocKyBus.getDshk(), namHocBus.getDsnh());
        
        
        DiemHocKiBUS diemHkBus = new DiemHocKiBUS();
        diemHkBus.docDSDHK(hsBus.getDshs(), mhBus.getDsmh(), hocKyBus.getDshk(), namHocBus.getDsnh());
        diemHkBus.tinhTbcMonHkToanDs();
        
        KetQuaHocTapHocKyBUS kqhthkBus = new KetQuaHocTapHocKyBUS();
        kqhthkBus.doc(hsBus.getDshs(), hocKyBus.getDshk(), namHocBus.getDsnh());
        kqhthkBus.tinhDtbHocKy();
        
        HocBaCuoiNamBUS hbcnBus = new HocBaCuoiNamBUS();
        hbcnBus.doc(hsBus.getDshs(), namHocBus.getDsnh());
        hbcnBus.tinhKetQuaHocTap();
        
        PhanCongCNBUS pccnBus = new PhanCongCNBUS();
        pccnBus.doc(namHocBus.getDsnh(), lopBus.getDslop(), gvBus.getDsgv());
        
        PhanCongGDBUS pcgdBus = new PhanCongGDBUS();
        pcgdBus.doc(hocKyBus.getDshk(), namHocBus.getDsnh(), lopBus.getDslop(), gvBus.getDsgv(), mhBus.getDsmh());
        
        TKBBUS tkbBus = new TKBBUS();
        tkbBus.doc(hocKyBus.getDshk(), namHocBus.getDsnh(), mhBus.getDsmh(), gvBus.getDsgv(), lopBus.getDslop());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel funPanel;
    private javax.swing.JLabel iconHeader;
    private javax.swing.JLabel iconTruong;
    private javax.swing.JPanel inPCGD;
    private javax.swing.JPanel inQLD;
    private javax.swing.JPanel inQLGV;
    private javax.swing.JPanel inQLHS;
    private javax.swing.JPanel inQLLH;
    private javax.swing.JPanel inQLMH;
    private javax.swing.JPanel inTKB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbPCGD;
    private javax.swing.JLabel lbTKB;
    private javax.swing.JPanel pnPCGD;
    private javax.swing.JPanel pnQLD;
    private javax.swing.JPanel pnQLGV;
    private javax.swing.JPanel pnQLHS;
    private javax.swing.JPanel pnQLLH;
    private javax.swing.JPanel pnQLMH;
    private javax.swing.JPanel pnTKB;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
