/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.DiemBUS;
import BusinessLogicLayer.DiemHocKiBUS;
import BusinessLogicLayer.HS_LopBUS;
import BusinessLogicLayer.HocBaCuoiNamBUS;
import BusinessLogicLayer.HocKyBUS;
import BusinessLogicLayer.HocSinhBUS;
import BusinessLogicLayer.KetQuaHocTapHocKyBUS;
import BusinessLogicLayer.LoaiDiemBUS;
import BusinessLogicLayer.LopBUS;
import BusinessLogicLayer.MonHocBUS;
import BusinessLogicLayer.NamHocBUS;
import DataTransferObject.DiemDTO;
import DataTransferObject.DiemHocKiDTO;
import DataTransferObject.HS_LopDTO;
import DataTransferObject.HocBaCuoiNamDTO;
import DataTransferObject.HocKyDTO;
import DataTransferObject.HocSinhDTO;
import DataTransferObject.KetQuaHocTapHocKiDTO;
import DataTransferObject.LoaiDiemDTO;
import DataTransferObject.MonHocDTO;
import DataTransferObject.NamHocDTO;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mr932
 */
public class QuanLyChuNhiemGUI extends javax.swing.JInternalFrame {
    private final static int FRAME_TTHS_HEIGHT = 376;
    private final static int FRAME_TTHS_WIDTH = 880;
    private final static int FRAME_DIEMCHITIET_HEIGHT = 711;
    private final static int FRAME_DIEMCHITIET_WIDTH = 880;
    /**
     * Creates new form QuanLyChuNhiemGUI
     */
    ArrayList<String> dsDanhGia;
    NamHocBUS nhBus;
    LopBUS lopBus;
    KetQuaHocTapHocKyBUS kqhthkBus;
    HS_LopBUS hslopBus;
    HocKyBUS hkBus;
    LoaiDiemBUS ldBus;
    MonHocBUS mhBus;
    HocBaCuoiNamBUS hbcnBus;
    DiemBUS diemBus;
    DiemHocKiBUS dhkBus;
    HocSinhBUS hsBus;
    public QuanLyChuNhiemGUI() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        dsDanhGia = new ArrayList<>();
        dsDanhGia.add("Tot");
        dsDanhGia.add("Kha");
        dsDanhGia.add("Trung Binh");
        dsDanhGia.add("Yeu");
        hsBus = new HocSinhBUS();
        hslopBus = new HS_LopBUS();
        nhBus = new NamHocBUS();
        lopBus = new LopBUS();
        diemBus = new DiemBUS();
        dhkBus = new DiemHocKiBUS();
        kqhthkBus = new KetQuaHocTapHocKyBUS();
        hbcnBus = new HocBaCuoiNamBUS();
        hkBus = new HocKyBUS();
        mhBus = new MonHocBUS();
        ldBus = new LoaiDiemBUS();
        TienIch.duaGiaTriVaoCbx(cbxNamHoc, nhBus.toStringList(nhBus.getDsnh()));
        TienIch.duaGiaTriVaoCbx(cbxLopHoc, lopBus.toStringList(lopBus.getDslop()));
        TienIch.duaGiaTriVaoCbx(cbxHanhKiem, dsDanhGia);
        kqhthkBus = new KetQuaHocTapHocKyBUS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgHk = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        cbxLopHoc = new javax.swing.JComboBox<>();
        cbxNamHoc = new javax.swing.JComboBox<>();
        lbTenGiaoVien1 = new javax.swing.JLabel();
        lbSoHocSinh1 = new javax.swing.JLabel();
        functionPanel = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        btnDiemChiTiet = new javax.swing.JButton();
        txTen = new javax.swing.JTextField();
        lbMa = new javax.swing.JLabel();
        lbHo = new javax.swing.JLabel();
        btnHocBa = new javax.swing.JButton();
        btnDocDS = new javax.swing.JButton();
        lbHocKy = new javax.swing.JLabel();
        radHk1 = new javax.swing.JRadioButton();
        radHk2 = new javax.swing.JRadioButton();
        txMa = new javax.swing.JTextField();
        lbMa1 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        lbDiemTbBeHon = new javax.swing.JLabel();
        txDiemTbBeHon = new javax.swing.JTextField();
        lbDiemTbLonHon = new javax.swing.JLabel();
        txDiemTbLonHon = new javax.swing.JTextField();
        cbxHanhKiem = new javax.swing.JComboBox<>();
        lbTen = new javax.swing.JLabel();
        btnLuuHanhKiem = new javax.swing.JButton();
        lbXepLoai = new javax.swing.JLabel();
        btnTinhXepLoai = new javax.swing.JButton();
        txHo = new javax.swing.JTextField();
        txDiemTbBang = new javax.swing.JTextField();
        btnNhapLai = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        scrollPaneDsKetQuaHocTap = new javax.swing.JScrollPane();
        tbDsKetQuaHocTap = new javax.swing.JTable();
        btnReport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        lbSoKetQuaTimThay = new javax.swing.JLabel();
        btnChuyenHs = new javax.swing.JButton();

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        headerLabel.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(23, 35, 51));
        headerLabel.setText("Quản Lý Lớp Chủ Nhiệm");

        cbxLopHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxLopHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbTenGiaoVien1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTenGiaoVien1.setForeground(new java.awt.Color(23, 35, 51));
        lbTenGiaoVien1.setText("Năm học");

        lbSoHocSinh1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbSoHocSinh1.setForeground(new java.awt.Color(23, 35, 51));
        lbSoHocSinh1.setText("Lớp học");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSoHocSinh1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTenGiaoVien1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxNamHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLopHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenGiaoVien1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoHocSinh1))
                        .addGap(12, 12, 12))))
        );

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        btnDiemChiTiet.setBackground(new java.awt.Color(23, 35, 51));
        btnDiemChiTiet.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDiemChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnDiemChiTiet.setText("Điểm chi tiết");
        btnDiemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemChiTietActionPerformed(evt);
            }
        });

        txTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTenActionPerformed(evt);
            }
        });

        lbMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMa.setForeground(new java.awt.Color(23, 35, 51));
        lbMa.setText("Họ");

        lbHo.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHo.setForeground(new java.awt.Color(23, 35, 51));
        lbHo.setText("Tên");

        btnHocBa.setBackground(new java.awt.Color(23, 35, 51));
        btnHocBa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnHocBa.setForeground(new java.awt.Color(255, 255, 255));
        btnHocBa.setText("Học bạ cả năm");
        btnHocBa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocBaActionPerformed(evt);
            }
        });

        btnDocDS.setBackground(new java.awt.Color(120, 168, 252));
        btnDocDS.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDocDS.setForeground(new java.awt.Color(255, 255, 255));
        btnDocDS.setText("Đọc DS");
        btnDocDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDSActionPerformed(evt);
            }
        });

        lbHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbHocKy.setText("Học kỳ");

        btgHk.add(radHk1);
        radHk1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk1.setText("1");
        radHk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHk1ActionPerformed(evt);
            }
        });

        btgHk.add(radHk2);
        radHk2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk2.setText("2");
        radHk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHk2ActionPerformed(evt);
            }
        });

        txMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMaActionPerformed(evt);
            }
        });

        lbMa1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMa1.setForeground(new java.awt.Color(23, 35, 51));
        lbMa1.setText("Mã");

        btnTimKiem.setBackground(new java.awt.Color(23, 35, 51));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        lbDiemTbBeHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiemTbBeHon.setText("Điểm TB bé hơn");

        txDiemTbBeHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txDiemTbBeHon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txDiemTbBeHon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiemTbBeHonActionPerformed(evt);
            }
        });

        lbDiemTbLonHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiemTbLonHon.setText("Điểm TB lớn hơn");

        txDiemTbLonHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txDiemTbLonHon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txDiemTbLonHon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiemTbLonHonActionPerformed(evt);
            }
        });

        cbxHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxHanhKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTen.setForeground(new java.awt.Color(23, 35, 51));
        lbTen.setText("Hạnh kiểm");

        btnLuuHanhKiem.setBackground(new java.awt.Color(23, 35, 51));
        btnLuuHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnLuuHanhKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuHanhKiem.setText("Lưu hạnh kiểm");
        btnLuuHanhKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHanhKiemActionPerformed(evt);
            }
        });

        lbXepLoai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbXepLoai.setText("Điểm TB bằng");

        btnTinhXepLoai.setBackground(new java.awt.Color(23, 35, 51));
        btnTinhXepLoai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnTinhXepLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhXepLoai.setText("Tính xếp loại");
        btnTinhXepLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhXepLoaiActionPerformed(evt);
            }
        });

        txHo.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHoActionPerformed(evt);
            }
        });

        txDiemTbBang.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txDiemTbBang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txDiemTbBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiemTbBangActionPerformed(evt);
            }
        });

        btnNhapLai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbMa)
                        .addGap(120, 120, 120))
                    .addComponent(txHo)
                    .addComponent(txMa)
                    .addComponent(txTen)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMa1)
                            .addComponent(lbHo))
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txDiemTbBeHon, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbDiemTbBeHon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbXepLoai)
                            .addComponent(txDiemTbBang, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbTen)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txDiemTbLonHon, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbDiemTbLonHon, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lbHocKy)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(radHk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radHk2))
                    .addComponent(btnNhapLai))
                .addGap(56, 56, 56)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTinhXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHocBa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocDS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(lbDiemTbBeHon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txDiemTbBeHon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(lbDiemTbLonHon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txDiemTbLonHon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbXepLoai)
                        .addGap(100, 100, 100))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbMa1)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txMa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDocDS)
                                    .addComponent(btnTinhXepLoai))))
                        .addGap(21, 21, 21)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelInputLayout.createSequentialGroup()
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelInputLayout.createSequentialGroup()
                                            .addComponent(lbMa)
                                            .addGap(7, 7, 7)
                                            .addComponent(txHo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnTimKiem)
                                            .addComponent(btnDiemChiTiet)))
                                    .addGap(24, 24, 24)
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelInputLayout.createSequentialGroup()
                                            .addComponent(lbHo)
                                            .addGap(7, 7, 7)
                                            .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnHocBa)))
                                .addGroup(panelInputLayout.createSequentialGroup()
                                    .addComponent(lbHocKy)
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInputLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(radHk1)
                                                .addComponent(radHk2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTen)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cbxHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnNhapLai)))
                                        .addGroup(panelInputLayout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(txDiemTbBang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addComponent(btnLuuHanhKiem, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(25, 25, 25))
        );

        panelTable.setBackground(new java.awt.Color(255, 255, 255));
        panelTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        scrollPaneDsKetQuaHocTap.setToolTipText("");
        scrollPaneDsKetQuaHocTap.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDsKetQuaHocTap.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDsKetQuaHocTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ", "Tên", "Hạnh kiểm", "Điểm trung bình", "Xếp loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDsKetQuaHocTap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDsKetQuaHocTaptbDSDSmouseClick(evt);
            }
        });
        scrollPaneDsKetQuaHocTap.setViewportView(tbDsKetQuaHocTap);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneDsKetQuaHocTap, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scrollPaneDsKetQuaHocTap, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        );

        btnReport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnReport.setText("Report");

        btnExport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnExport.setText("Export");

        btnImport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnImport.setText("Import");

        lbSoKetQuaTimThay.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbSoKetQuaTimThay.setText("Số kết quả tìm thấy");

        btnChuyenHs.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnChuyenHs.setText("Chuyển Học Sinh");
        btnChuyenHs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenHsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lbSoKetQuaTimThay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImport)
                .addGap(18, 18, 18)
                .addComponent(btnExport)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChuyenHs, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnChuyenHs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReport)
                    .addComponent(btnExport)
                    .addComponent(btnImport)
                    .addComponent(lbSoKetQuaTimThay))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTenActionPerformed

    private void tbDsKetQuaHocTaptbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDsKetQuaHocTaptbDSDSmouseClick
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDsKetQuaHocTaptbDSDSmouseClick

    private void txDiemTbBeHonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiemTbBeHonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiemTbBeHonActionPerformed

    private void radHk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHk1ActionPerformed

    private void radHk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHk2ActionPerformed

    private void txDiemTbLonHonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiemTbLonHonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiemTbLonHonActionPerformed

    private void txMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMaActionPerformed

    private void btnDiemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemChiTietActionPerformed
        // TODO add your handling code here:
        int row = tbDsKetQuaHocTap.getSelectedRow();
        if (row >= 0){
            String maHs = (String) tbDsKetQuaHocTap.getModel().getValueAt(row, 1);
            String maHocKy = (String) tbDsKetQuaHocTap.getModel().getValueAt(row, 5);
            String namHoc = (String) tbDsKetQuaHocTap.getModel().getValueAt(row, 6);
            KetQuaHocTapHocKiDTO kqhthkCanShow = kqhthkBus.timKiemKqhthk(maHs, maHocKy, namHoc);
            SubFrameDiemChiTietHocSinh frameDiemChiTiet = new SubFrameDiemChiTietHocSinh(kqhthkCanShow);
            frameDiemChiTiet.setSize(FRAME_DIEMCHITIET_WIDTH, FRAME_DIEMCHITIET_HEIGHT);
            frameDiemChiTiet.setVisible(true);
        }
    }//GEN-LAST:event_btnDiemChiTietActionPerformed

    private void btnDocDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDSActionPerformed
        try {
            // TODO add your handling code here:
            doc();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyChuNhiemGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDocDSActionPerformed

    private void btnHocBaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocBaActionPerformed
        // TODO add your handling code here:
        SubFrameHocBa frameHocBa = new SubFrameHocBa((String) cbxLopHoc.getSelectedItem(), (String) cbxNamHoc.getSelectedItem());
        frameHocBa.setSize(FRAME_DIEMCHITIET_WIDTH, FRAME_DIEMCHITIET_HEIGHT);
        frameHocBa.setVisible(true);
    }//GEN-LAST:event_btnHocBaActionPerformed

    private void btnLuuHanhKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHanhKiemActionPerformed
        try {
            // TODO add your handling code here:
            luu();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyChuNhiemGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuHanhKiemActionPerformed

    private void btnTinhXepLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhXepLoaiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTinhXepLoaiActionPerformed

    private void txHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHoActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txDiemTbBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiemTbBangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiemTbBangActionPerformed

    private void btnChuyenHsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenHsActionPerformed
        // TODO add your handling code here:
        int row = tbDsKetQuaHocTap.getSelectedRow();
        String namHoc = (String) cbxNamHoc.getSelectedItem();
        if (namHoc.equals(""))
            JOptionPane.showMessageDialog(null, "Hãy chọn năm học.");
        if (row >= 0 && !namHoc.equals("")){
            String maHsCanXoa = tbDsKetQuaHocTap.getModel().getValueAt(row, 1).toString();
            DefaultTableModel model = (DefaultTableModel) tbDsKetQuaHocTap.getModel();
            model.removeRow(row);
            tbDsKetQuaHocTap.setModel(model);
            HocSinhDTO hs = hsBus.timKiemHocSinh(maHsCanXoa);
            NamHocDTO nh = nhBus.timKiemNamHoc(namHoc);
            
        for (HocKyDTO hkDto : hkBus.getDshk()) {
                KetQuaHocTapHocKiDTO kqhthk = new KetQuaHocTapHocKiDTO();
                
                HS_LopDTO hslop = new HS_LopDTO();
                

                for (MonHocDTO mh : mhBus.getDsmh()) {
                    DiemHocKiDTO diemHk = new DiemHocKiDTO();

                    for (LoaiDiemDTO ld : ldBus.getDsld()) {
                        DiemDTO diem = new DiemDTO();
                        diem.setHocSinh(hs);
                        diem.setHocKy(hkDto);
                        diem.setNamHoc(nh);
                        diem.setLoaiDiem(ld);
                        diem.setMonHoc(mh);
                        try {
                            diemBus.xoa(diem);
                        } catch (Exception ex) {
                            Logger.getLogger(QuanLyHocSinhGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    diemHk.setHocKy(hkDto);
                    diemHk.setHocSinh(hs);
                    diemHk.setNamHoc(nh);
                    diemHk.setMonHoc(mh);
                    try {
                        dhkBus.xoa(diemHk);
                    } catch (Exception ex) {
                        Logger.getLogger(QuanLyHocSinhGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                kqhthk.setHocKy(hkDto);
                kqhthk.setNamHoc(nh);
                kqhthk.setHocSinh(hs);
                
                hslop.setNh(nh);
                hslop.setHs(hs);
                hslop.setHk(hkDto);
                hslopBus.xoa(hslop);
                
                try {
                    kqhthkBus.xoa(kqhthk);
                } catch (Exception ex) {
                    Logger.getLogger(QuanLyHocSinhGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            HocBaCuoiNamDTO hbcn = new HocBaCuoiNamDTO();
            hbcn.setHocSinh(hs);
            hbcn.setNamHoc(nh);
            
            try {
                hbcnBus.xoa(hbcn);
            } catch (Exception ex) {
                Logger.getLogger(QuanLyHocSinhGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnChuyenHsActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        resetAllField();
    }//GEN-LAST:event_btnNhapLaiActionPerformed
    
    private void resetAllField(){
        cbxHanhKiem.setSelectedIndex(0);
        txMa.setText("");
        txHo.setText("");
        txTen.setText("");
        txDiemTbBeHon.setText("");
        txDiemTbLonHon.setText("");
        txDiemTbBang.setText("");
        radHk1.setSelected(false);
        radHk2.setSelected(false);
    }
    private void timKiem(){
        if (kiemTraDauVao()){
            ArrayList<KetQuaHocTapHocKiDTO> dsKetQua = kqhthkBus.getDskqhthk();
            String ma = TienIch.chuanHoa(txMa.getText());
            String ho = TienIch.chuanHoa(txHo.getText());
            String ten = TienIch.chuanHoa(txTen.getText());
            String namHoc = (String) cbxNamHoc.getSelectedItem();
            String hanhKiem = (String) cbxHanhKiem.getSelectedItem();
            String maLopDuocChon = (String) cbxLopHoc.getSelectedItem();
            
            if (!maLopDuocChon.equals("")){
                ArrayList<KetQuaHocTapHocKiDTO> dsKetQuaMoi = new ArrayList<>();
                for (KetQuaHocTapHocKiDTO kqhthk : dsKetQua){
                    String malop = "";
                    if (hslopBus.timHocSinhLop(kqhthk.getHocSinh(), kqhthk.getHocKy(), kqhthk.getNamHoc()) == null){
                        System.out.println(kqhthk.getHocSinh().getMahs());
                        System.out.println(kqhthk.getHocKy().getMahk());
                        System.out.println(kqhthk.getNamHoc().getManh());
                        System.out.println("Khoong tim thay HS_Lop trong Danh Sach DiemHocKi");
                    }
                    else
                        malop = hslopBus.timHocSinhLop(kqhthk.getHocSinh(), kqhthk.getHocKy(), kqhthk.getNamHoc()).getLop().getMalop();
                    if (maLopDuocChon.equals(malop))
                        dsKetQuaMoi.add(kqhthk);
                }
                dsKetQua = dsKetQuaMoi;
            }
            
            if (!ma.equals(""))
                dsKetQua = kqhthkBus.timKiemTheoMaHocSinh(ma, dsKetQua);
            
            if (!ho.equals(""))
                dsKetQua = kqhthkBus.timKiemTheoHoHocSinh(ho, dsKetQua);
            
            if (!ten.equals(""))
                dsKetQua = kqhthkBus.timKiemTheoTenHocSinh(ten, dsKetQua);
            
            if (!namHoc.equals(""))
                dsKetQua = kqhthkBus.timKiemTheoNamHoc(namHoc, dsKetQua);
            
            if (!hanhKiem.equals(""))
                dsKetQua = kqhthkBus.timKiemTheoHanhKiem(hanhKiem, dsKetQua);
            
            if (!txDiemTbBeHon.getText().equals(""))
                dsKetQua = kqhthkBus.timKiemDiemNhoHon(Float.parseFloat(txDiemTbBeHon.getText()), dsKetQua);
            
            if (!txDiemTbLonHon.getText().equals(""))
                dsKetQua = kqhthkBus.timKiemDiemLonHon(Float.parseFloat(txDiemTbLonHon.getText()), dsKetQua);
            
            if (!txDiemTbBang.getText().equals(""))
                dsKetQua = kqhthkBus.timKiemDiem(Float.parseFloat(txDiemTbBang.getText()), dsKetQua);
            
            if (radHk1.isSelected())
                dsKetQua = kqhthkBus.timKiemTheoHocKy(radHk1.getText(), dsKetQua);
            
            if (radHk2.isSelected())
                dsKetQua = kqhthkBus.timKiemTheoHocKy(radHk2.getText(), dsKetQua);
            
            
            
            showTable(dsKetQua);
        }
    }
    
    private Boolean kiemTraDauVao() {
        String thongBao = "";
        int sttThongBao = 1;
        Boolean dauVao = true;
        
        if (!TienIch.isStringFloat(txDiemTbBeHon.getText()) && !txDiemTbBeHon.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". Ô điểm trung bình bé hơn hoặc bằng phải là số thực.\n";
            sttThongBao++;
        }

        if (!TienIch.isStringFloat(txDiemTbLonHon.getText()) && !txDiemTbLonHon.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". Ô điểm trung bình lớn hơn hoặc bằng phải là số thực.\n";
            sttThongBao++;
        }
        
        if (!TienIch.isStringFloat(txDiemTbBang.getText()) && !txDiemTbBang.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". Ô điểm trung bình bằng phải là số thực.\n";
            sttThongBao++;
        }

        if (!thongBao.equals("")) {
            JOptionPane.showMessageDialog(null, thongBao);
        }
        return dauVao;
    }
    
    private void luu() throws Exception{
        int row = tbDsKetQuaHocTap.getSelectedRow();
        if (row >= 0){
            String maHs = (String) tbDsKetQuaHocTap.getModel().getValueAt(row, 1);
            String maHocKy = (String) tbDsKetQuaHocTap.getModel().getValueAt(row, 5);
            String namHoc = (String) tbDsKetQuaHocTap.getModel().getValueAt(row, 6);
            String hanhKiem = (String) cbxHanhKiem.getSelectedItem();
            KetQuaHocTapHocKiDTO kqhthkCanSua = kqhthkBus.timKiemKqhthk(maHs, maHocKy, namHoc);
            kqhthkCanSua.setHanhKiem(hanhKiem);
            kqhthkBus.sua(kqhthkCanSua);
            tbDsKetQuaHocTap.setValueAt(hanhKiem, row, 8);
        }
    }
    
    private void doc() throws Exception{
        kqhthkBus.tinhDtbHocKy();
        showTable(kqhthkBus.getDskqhthk());
    }
    
    private void showTable(ArrayList<KetQuaHocTapHocKiDTO> dskqhthk){
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã");
        header.add("Họ");
        header.add("Tên");
        header.add("Lớp");
        header.add("Học Kỳ");
        header.add("Năm Học");
        header.add("ĐTBHK");
        header.add("Hạnh Kiểm");
        int stt = 1;
        DefaultTableModel model = new DefaultTableModel(header, 0);
        for (KetQuaHocTapHocKiDTO kqhthk : dskqhthk){
            String tenLop = hslopBus.timHocSinhLop(kqhthk.getHocSinh(), kqhthk.getHocKy(), kqhthk.getNamHoc()).getLop().getTenlop();
            Vector row = new Vector();
            row.add(stt);
            row.add(kqhthk.getHocSinh().getMahs());
            row.add(kqhthk.getHocSinh().getHo());
            row.add(kqhthk.getHocSinh().getTen());
            row.add(tenLop);
            row.add(kqhthk.getHocKy().getMahk());
            row.add(kqhthk.getNamHoc().getTennh());
            row.add(kqhthk.getTbcHocky());
            row.add(kqhthk.getHanhKiem());
            model.addRow(row);
            stt++;
        }
        tbDsKetQuaHocTap.setModel(model);
        lbSoKetQuaTimThay.setText("Tìm thấy " + model.getRowCount() + " kết quả.");
    }
    private void openJInternalFrame(JInternalFrame internalFrame){
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgHk;
    private javax.swing.JButton btnChuyenHs;
    private javax.swing.JButton btnDiemChiTiet;
    private javax.swing.JButton btnDocDS;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHocBa;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLuuHanhKiem;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTinhXepLoai;
    private javax.swing.JComboBox<String> cbxHanhKiem;
    private javax.swing.JComboBox<String> cbxLopHoc;
    private javax.swing.JComboBox<String> cbxNamHoc;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lbDiemTbBeHon;
    private javax.swing.JLabel lbDiemTbLonHon;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbHocKy;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbMa1;
    private javax.swing.JLabel lbSoHocSinh1;
    private javax.swing.JLabel lbSoKetQuaTimThay;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbTenGiaoVien1;
    private javax.swing.JLabel lbXepLoai;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelTable;
    private javax.swing.JRadioButton radHk1;
    private javax.swing.JRadioButton radHk2;
    private javax.swing.JScrollPane scrollPaneDsKetQuaHocTap;
    private javax.swing.JTable tbDsKetQuaHocTap;
    private javax.swing.JTextField txDiemTbBang;
    private javax.swing.JTextField txDiemTbBeHon;
    private javax.swing.JTextField txDiemTbLonHon;
    private javax.swing.JTextField txHo;
    private javax.swing.JTextField txMa;
    private javax.swing.JTextField txTen;
    // End of variables declaration//GEN-END:variables
}
