/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.DiemBUS;
import BusinessLogicLayer.DiemHocKiBUS;
import BusinessLogicLayer.GiaoVienBUS;
import BusinessLogicLayer.HS_LopBUS;
import BusinessLogicLayer.HocKyBUS;
import BusinessLogicLayer.HocSinhBUS;
import BusinessLogicLayer.LoaiDiemBUS;
import BusinessLogicLayer.LopBUS;
import BusinessLogicLayer.MonHocBUS;
import BusinessLogicLayer.NamHocBUS;
import DataTransferObject.DiemDTO;
import DataTransferObject.DiemHocKiDTO;
import DataTransferObject.HS_LopDTO;
import DataTransferObject.KetQuaHocTapHocKiDTO;
import DataTransferObject.LoaiDiemDTO;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mr932
 */
public class QuanLyDiemBoMonGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyDiemBoMonGUI
     */
    LopBUS lopBus;
    NamHocBUS namHocBus;
    DiemBUS diemBus;
    DiemHocKiBUS diemHkBus;
    HS_LopBUS hslopBus;
    MonHocBUS mhBus;
    HocSinhBUS hsBus;
    NamHocBUS nhBus;
    HocKyBUS hkBus;
    LoaiDiemBUS ldBus;
    GiaoVienBUS gvBus;
    public QuanLyDiemBoMonGUI() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
        lopBus = new LopBUS();
        namHocBus = new NamHocBUS();
        diemBus = new DiemBUS();
        diemHkBus = new DiemHocKiBUS();
        hslopBus = new HS_LopBUS();
        mhBus = new MonHocBUS();
        hsBus = new HocSinhBUS();
        nhBus = new NamHocBUS();
        hkBus = new HocKyBUS();
        ldBus = new LoaiDiemBUS();
        gvBus = new GiaoVienBUS();
        TienIch.duaGiaTriVaoCbx(cbxLopHoc, lopBus.toStringList(lopBus.getDslop()));
        TienIch.duaGiaTriVaoCbx(cbxNamHoc, namHocBus.toStringList(namHocBus.getDsnh()));
        TienIch.duaGiaTriVaoCbx(cbxMonPhuTrach, mhBus.toStringList(mhBus.getDsmh()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgHk = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbxMonPhuTrach = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnChonLop = new javax.swing.JButton();
        functionPanel = new javax.swing.JPanel();
        scrollPaneDiemTbMonTungHocSinh = new javax.swing.JScrollPane();
        tbDiemTbMonTungHocSinh = new javax.swing.JTable();
        panelInput = new javax.swing.JPanel();
        lbLop = new javax.swing.JLabel();
        lbHocKy = new javax.swing.JLabel();
        lbNamHoc = new javax.swing.JLabel();
        cbxNamHoc = new javax.swing.JComboBox<>();
        cbxLopHoc = new javax.swing.JComboBox<>();
        radHk1 = new javax.swing.JRadioButton();
        radHk2 = new javax.swing.JRadioButton();
        btnDocDanhSach = new javax.swing.JButton();
        txMa = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txHo = new javax.swing.JTextField();
        txTen = new javax.swing.JTextField();
        lbHo = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbDtbBang = new javax.swing.JLabel();
        lbDiemTbLonHon = new javax.swing.JLabel();
        lbDtbBeHon = new javax.swing.JLabel();
        txDtbBeHon = new javax.swing.JTextField();
        txDtbLonHon = new javax.swing.JTextField();
        txDtbBang = new javax.swing.JTextField();
        btnNhapLai = new javax.swing.JButton();
        scrollPaneDiemChiTiet = new javax.swing.JScrollPane();
        tbDiemChiTiet = new javax.swing.JTable();
        panelInputDiem = new javax.swing.JPanel();
        lbDiem1Tiet = new javax.swing.JLabel();
        txDiem1Tiet = new javax.swing.JTextField();
        lbDiemThi = new javax.swing.JLabel();
        txDiemThi = new javax.swing.JTextField();
        lbDiem15Phut = new javax.swing.JLabel();
        txDiem15Phut = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnTinhDtb = new javax.swing.JButton();
        lbSoKetQuaTimThay = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(880, 800));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 35, 51));
        jLabel5.setText("Quản Lý Điểm Bộ Môn");

        cbxMonPhuTrach.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxMonPhuTrach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel2.setText("Môn học");

        btnChonLop.setText("...");
        btnChonLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(cbxMonPhuTrach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChonLop, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxMonPhuTrach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btnChonLop)))
                .addContainerGap())
        );

        scrollPaneDiemTbMonTungHocSinh.setToolTipText("");
        scrollPaneDiemTbMonTungHocSinh.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDiemTbMonTungHocSinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDiemTbMonTungHocSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ", "Tên", "Điểm TB Môn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDiemTbMonTungHocSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemTbMonTungHocSinhtbDSDSmouseClick(evt);
            }
        });
        scrollPaneDiemTbMonTungHocSinh.setViewportView(tbDiemTbMonTungHocSinh);

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        lbLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop.setForeground(new java.awt.Color(23, 35, 51));
        lbLop.setText("Lớp");

        lbHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbHocKy.setText("Học kỳ");

        lbNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc.setText("Năm học");

        cbxNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxLopHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxLopHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btgHk.add(radHk1);
        radHk1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk1.setText("1");
        radHk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHk1ActionPerformed(evt);
            }
        });

        btgHk.add(radHk2);
        radHk2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk2.setText("2");
        radHk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHk2ActionPerformed(evt);
            }
        });

        btnDocDanhSach.setBackground(new java.awt.Color(120, 168, 252));
        btnDocDanhSach.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDocDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDocDanhSach.setText("Đọc Danh Sách");
        btnDocDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDanhSachActionPerformed(evt);
            }
        });

        txMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txMa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(23, 35, 51));
        btnTimKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txHo.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        txTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        lbHo.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHo.setForeground(new java.awt.Color(23, 35, 51));
        lbHo.setText("Họ ");

        lbMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMa.setForeground(new java.awt.Color(23, 35, 51));
        lbMa.setText("Mã ");

        lbTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTen.setForeground(new java.awt.Color(23, 35, 51));
        lbTen.setText("Tên");

        lbDtbBang.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDtbBang.setForeground(new java.awt.Color(23, 35, 51));
        lbDtbBang.setText("ĐTB bằng");

        lbDiemTbLonHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiemTbLonHon.setForeground(new java.awt.Color(23, 35, 51));
        lbDiemTbLonHon.setText("ĐTB lớn hơn ");

        lbDtbBeHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDtbBeHon.setForeground(new java.awt.Color(23, 35, 51));
        lbDtbBeHon.setText("ĐTB bé hơn");

        txDtbBeHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txDtbBeHon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txDtbBeHon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDtbBeHonActionPerformed(evt);
            }
        });

        txDtbLonHon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txDtbLonHon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        txDtbBang.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txDtbBang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        btnNhapLai.setBackground(new java.awt.Color(23, 35, 51));
        btnNhapLai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnNhapLai.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHo)
                    .addComponent(lbMa)
                    .addComponent(lbTen))
                .addGap(18, 18, 18)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txHo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(txMa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTen))
                .addGap(34, 34, 34)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbHocKy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radHk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radHk2))
                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addComponent(lbLop)
                            .addGap(6, 6, 6)
                            .addComponent(cbxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelInputLayout.createSequentialGroup()
                            .addComponent(lbNamHoc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDiemTbLonHon)
                    .addComponent(lbDtbBeHon)
                    .addComponent(lbDtbBang))
                .addGap(18, 18, 18)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txDtbLonHon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDtbBeHon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDtbBang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDocDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbHo))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txMa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMa))
                                .addGap(18, 18, 18)
                                .addComponent(txHo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTen)))
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelInputLayout.createSequentialGroup()
                                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbHocKy)
                                            .addComponent(radHk1)
                                            .addComponent(radHk2))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbNamHoc))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInputLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(lbLop))
                                            .addComponent(cbxLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInputLayout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(lbDiemTbLonHon))
                                        .addGroup(panelInputLayout.createSequentialGroup()
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txDtbBeHon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbDtbBeHon)
                                                .addComponent(btnDocDanhSach))
                                            .addGap(18, 18, 18)
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txDtbLonHon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnNhapLai))
                                            .addGap(17, 17, 17)
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txDtbBang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbDtbBang)
                                                .addComponent(btnTimKiem)))))))))
                .addGap(25, 25, 25))
        );

        scrollPaneDiemChiTiet.setToolTipText("");
        scrollPaneDiemChiTiet.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDiemChiTiet.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDiemChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Loại điểm", "Hệ số", "Điểm số"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDiemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemChiTiettbDSDSmouseClick(evt);
            }
        });
        scrollPaneDiemChiTiet.setViewportView(tbDiemChiTiet);

        panelInputDiem.setBackground(new java.awt.Color(255, 255, 255));
        panelInputDiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        lbDiem1Tiet.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiem1Tiet.setForeground(new java.awt.Color(23, 35, 51));
        lbDiem1Tiet.setText("Điểm 1 tiết");

        txDiem1Tiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiem1TietActionPerformed(evt);
            }
        });

        lbDiemThi.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiemThi.setForeground(new java.awt.Color(23, 35, 51));
        lbDiemThi.setText("Điểm thi");

        lbDiem15Phut.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiem15Phut.setForeground(new java.awt.Color(23, 35, 51));
        lbDiem15Phut.setText("Điểm 15 phút");

        btnLuu.setBackground(new java.awt.Color(23, 35, 51));
        btnLuu.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnTinhDtb.setBackground(new java.awt.Color(120, 168, 252));
        btnTinhDtb.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnTinhDtb.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhDtb.setText("Tính ĐTB");
        btnTinhDtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhDtbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputDiemLayout = new javax.swing.GroupLayout(panelInputDiem);
        panelInputDiem.setLayout(panelInputDiemLayout);
        panelInputDiemLayout.setHorizontalGroup(
            panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputDiemLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInputDiemLayout.createSequentialGroup()
                        .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDiem15Phut)
                            .addComponent(lbDiemThi)
                            .addComponent(lbDiem1Tiet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txDiemThi)
                            .addComponent(txDiem1Tiet)
                            .addComponent(txDiem15Phut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInputDiemLayout.createSequentialGroup()
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTinhDtb)
                        .addGap(14, 14, 14))))
        );
        panelInputDiemLayout.setVerticalGroup(
            panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputDiemLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiem15Phut)
                    .addComponent(txDiem15Phut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiem1Tiet)
                    .addComponent(txDiem1Tiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiemThi)
                    .addComponent(txDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInputDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnTinhDtb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbSoKetQuaTimThay.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbSoKetQuaTimThay.setText("Số kết quả tìm thấy");

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addComponent(scrollPaneDiemTbMonTungHocSinh)
                        .addGap(18, 18, 18)
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPaneDiemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(panelInputDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panelInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lbSoKetQuaTimThay)
                .addGap(364, 675, Short.MAX_VALUE))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addComponent(scrollPaneDiemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(panelInputDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPaneDiemTbMonTungHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSoKetQuaTimThay)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDiemTbMonTungHocSinhtbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemTbMonTungHocSinhtbDSDSmouseClick
        // TODO add your handling code here:
        chonHocSinh();
    }//GEN-LAST:event_tbDiemTbMonTungHocSinhtbDSDSmouseClick

    private void tbDiemChiTiettbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemChiTiettbDSDSmouseClick
        // TODO add your handling code here:
        chonDiemChiTiet();
    }//GEN-LAST:event_tbDiemChiTiettbDSDSmouseClick

    private void txDiem1TietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiem1TietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiem1TietActionPerformed

    private void radHk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHk1ActionPerformed

    private void radHk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHk2ActionPerformed

    private void btnDocDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDanhSachActionPerformed
        // TODO add your handling code here:
        doc();
    }//GEN-LAST:event_btnDocDanhSachActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            // TODO add your handling code here:
            luuDiem();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyDiemBoMonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void txMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMaActionPerformed

    private void txDtbBeHonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDtbBeHonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDtbBeHonActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTinhDtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhDtbActionPerformed
        try {
            // TODO add your handling code here:
            tdbMotHocSinh();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyDiemBoMonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTinhDtbActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        resetAllField();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnChonLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonLopActionPerformed
        // TODO add your handling code here:
        SubFrameChonMon frameChonMon = new SubFrameChonMon(cbxMonPhuTrach);
        frameChonMon.setSize(767, 462);
        frameChonMon.setVisible(true);
    }//GEN-LAST:event_btnChonLopActionPerformed
    
    private void resetAllField(){
        txMa.setText("");
        txHo.setText("");
        txTen.setText("");
        radHk1.setSelected(false);
        radHk2.setSelected(false);
        cbxNamHoc.setSelectedIndex(0);
        cbxLopHoc.setSelectedIndex(0);
    }
    
    private void tdbMotHocSinh() throws Exception{
        int row = tbDiemTbMonTungHocSinh.getSelectedRow();
        if (row >= 0){
            String mahs = (String) tbDiemTbMonTungHocSinh.getModel().getValueAt(row, 1);
            String mon = (String) tbDiemTbMonTungHocSinh.getModel().getValueAt(row, 5);
            String hk = (String) tbDiemTbMonTungHocSinh.getModel().getValueAt(row, 7);
            String nh = (String) tbDiemTbMonTungHocSinh.getModel().getValueAt(row, 8);
            float diemTb = diemHkBus.tinhDtbMonHkHs(mahs, mon, hk, nh);
            diemTb = (float) Math.round(diemTb * 10) / 10;
            tbDiemTbMonTungHocSinh.getModel().setValueAt(diemTb, row, 6);
        }
    }
    
    private void timKiem(){
        if (kiemTraDauVao()){
            ArrayList<DiemHocKiDTO> dskq = diemHkBus.getDsdhk();
            String ma = TienIch.chuanHoa(txMa.getText());
            String ho = TienIch.chuanHoa(txHo.getText());
            String ten = TienIch.chuanHoa(txTen.getText());
            String namHoc = (String) cbxNamHoc.getSelectedItem();
            String mon = (String) cbxMonPhuTrach.getSelectedItem();
            
            String maLopDuocChon = (String) cbxLopHoc.getSelectedItem();
            
            if (!maLopDuocChon.equals("")){
                ArrayList<DiemHocKiDTO> dsKetQuaMoi = new ArrayList<>();
                for (DiemHocKiDTO dhk : dskq){
                    String malop = "";
                    if(hslopBus.timHocSinhLop(dhk.getHocSinh().getMahs(), dhk.getHocKy().getMahk(), dhk.getNamHoc().getManh()) == null){
                        System.out.println(dhk.getHocSinh().getMahs());
                        System.out.println(dhk.getHocKy().getMahk());
                        System.out.println(dhk.getNamHoc().getManh());
                        System.out.println("Khoong tim thay HS_Lop trong Danh Sach DiemHocKi");
                    }
                    else
                        malop = hslopBus.timHocSinhLop(dhk.getHocSinh().getMahs(), dhk.getHocKy().getMahk(), dhk.getNamHoc().getManh()).getLop().getMalop();
                    if (maLopDuocChon.equals(malop))
                        dsKetQuaMoi.add(dhk);
                }
                dskq = dsKetQuaMoi;
            }
            
            if (!ma.equals(""))
                dskq = diemHkBus.timKiemTheoMaHocSinh(ma, dskq);
            
            if (!ho.equals(""))
                dskq = diemHkBus.timKiemTheoHoHocSinh(ho, dskq);
            
            if (!ten.equals(""))
                dskq = diemHkBus.timKiemTheoTenHocSinh(ten, dskq);
            
            if (!namHoc.equals(""))
                dskq = diemHkBus.timKiemTheoNamHoc(namHoc, dskq);
            
            if (!mon.equals(""))
                dskq = diemHkBus.timKiemTheoMonHoc(mon, dskq);
            
            if (!txDtbBeHon.getText().equals(""))
                dskq = diemHkBus.timKiemDiemNhoHon(Float.parseFloat(txDtbBeHon.getText()), dskq);
            
            if (!txDtbLonHon.getText().equals(""))
                dskq = diemHkBus.timKiemDiemLonHon(Float.parseFloat(txDtbLonHon.getText()), dskq);
            
            if (!txDtbBang.getText().equals(""))
                dskq = diemHkBus.timKiemDiemBang(Float.parseFloat(txDtbBang.getText()), dskq);
            
            if (radHk1.isSelected())
                dskq = diemHkBus.timKiemTheoHocKy(radHk1.getText(), dskq);
            
            if (radHk2.isSelected())
                dskq = diemHkBus.timKiemTheoHocKy(radHk2.getText(), dskq);
            
            showTableDiemHk(dskq);
        }
    }
    
    private void doc(){
        showTableDiemHk(diemHkBus.getDsdhk());
    }
    
    private void showTableDiemHk(ArrayList<DiemHocKiDTO> dsdhk){
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã");
        header.add("Họ");
        header.add("Tên");
        header.add("Lớp");
        header.add("Môn Học");
        header.add("Điểm số");
        header.add("Học Kỳ");
        header.add("Năm Học");
        DefaultTableModel model = new DefaultTableModel(header, 0);
        int stt = 1;
        for (DiemHocKiDTO diemhk : dsdhk) {
            HS_LopDTO hslop = hslopBus.timHocSinhLop(diemhk.getHocSinh().getMahs(), diemhk.getHocKy().getMahk(), diemhk.getNamHoc().getManh());
            Vector row = new Vector();
            row.add(stt);
            row.add(diemhk.getHocSinh().getMahs());
            row.add(diemhk.getHocSinh().getHo());
            row.add(diemhk.getHocSinh().getTen());
            if (hslop != null) {
                row.add(hslop.getLop().getTenlop()); // Tìm lớp
            } else {
                row.add("Chưa tìm được");
            }
            row.add(diemhk.getMonHoc().getTenmh());
            //row.add("Chưa tìm được"); // Tìm GVGD
            row.add(diemhk.getTbMonhk());
            row.add(diemhk.getHocKy().getMahk());
            row.add(diemhk.getNamHoc().getTennh());
            model.addRow(row);
            stt++;
        }
        tbDiemTbMonTungHocSinh.setModel(model);
        lbSoKetQuaTimThay.setText("Tìm thấy " + model.getRowCount() + " kết quả.");
    }
    
    private void showTableDiemChiTiet(ArrayList<DiemDTO> dsd){
        Vector header = new Vector();
        header.add("Loại Điểm");
        header.add("Hệ số");
        header.add("Điểm số");
        DefaultTableModel model = new DefaultTableModel(header, 0);
        int stt = 1;
        for (DiemDTO diem : dsd) {
            //HS_LopDTO hslop = hslopBus.timHocSinhLop(diem.getHocSinh().getMahs(), diem.getHocKy().getMahk(), diem.getNamHoc().getManh());
            Vector row = new Vector();
            row.add(diem.getLoaiDiem().getTenLoaiDiem());
            row.add(diem.getLoaiDiem().getHeSo());
            row.add(diem.getDiemSo());
            model.addRow(row);
            stt++;
        }
        tbDiemChiTiet.setModel(model);
    }
    
    private void chonHocSinh(){
        int i = tbDiemTbMonTungHocSinh.getSelectedRow();
        ArrayList<DiemDTO> bangDiemChiTiet = diemBus.getDsd();
        if (i >= 0) {
            String maHs = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 1).toString();
            System.out.println(maHs);
            bangDiemChiTiet = diemBus.timKiemTheoMaHocSinh(maHs, bangDiemChiTiet);
            String tenMh = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 5).toString();
            System.out.println(tenMh);
            bangDiemChiTiet = diemBus.timKiemTheoMonHoc(tenMh, bangDiemChiTiet);
            String maHk = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 7).toString();
            System.out.println(maHk);
            bangDiemChiTiet = diemBus.timKiemTheoHocKy(maHk, bangDiemChiTiet);
            String tenNh = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 8).toString();
            System.out.println(tenNh);
            bangDiemChiTiet = diemBus.timKiemTheoNamHoc(tenNh, bangDiemChiTiet);
            //System.out.println(bangDiemChiTiet.size());
        }
        showTableDiemChiTiet(bangDiemChiTiet);
    }
    
    private void chonDiemChiTiet(){
        int i = tbDiemChiTiet.getSelectedRow();
        if (i >= 0){
            txDiem15Phut.setText(tbDiemChiTiet.getModel().getValueAt(0, 2).toString());
            txDiem1Tiet.setText(tbDiemChiTiet.getModel().getValueAt(1, 2).toString());
            txDiemThi.setText(tbDiemChiTiet.getModel().getValueAt(2, 2).toString());
        }
    }
    
    private void luuDiem() throws Exception{
        int i = tbDiemTbMonTungHocSinh.getSelectedRow();
        if (kiemTraDauVaoLuuDiem() && i >= 0){
            
            String maHs = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 1).toString();
            String tenMh = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 5).toString();
            String maHk = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 7).toString();
            String tenNh = tbDiemTbMonTungHocSinh.getModel().getValueAt(i, 8).toString();
            int soCotDiem = tbDiemChiTiet.getRowCount();
            
            DefaultTableModel model = (DefaultTableModel) tbDiemChiTiet.getModel();
            model.setValueAt(TienIch.chuanHoa(txDiem15Phut.getText()), 0, 2);
            model.setValueAt(TienIch.chuanHoa(txDiem1Tiet.getText()), 1, 2);
            model.setValueAt(TienIch.chuanHoa(txDiemThi.getText()), 2, 2);
            tbDiemChiTiet.setModel(model);
            
            for (int j = 0; j < soCotDiem; j++){
                String tenLoaiDiem = tbDiemChiTiet.getModel().getValueAt(j, 0).toString();
                float diemSo = Float.parseFloat(tbDiemChiTiet.getModel().getValueAt(j, 2).toString());
                DiemDTO diemCanLuu = diemBus.timKiemDiem(maHs, maHk, tenNh, tenMh, tenLoaiDiem);
                diemCanLuu.setDiemSo(diemSo);
                diemBus.sua(diemCanLuu);
            }
        }
    }
    
    private Boolean kiemTraDauVaoLuuDiem() {
        String thongBao = "";
        int sttThongBao = 1;
        Boolean dauVao = true;
        
        if (!TienIch.isStringFloat(txDiem15Phut.getText()) && !txDiem15Phut.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". [Ô điểm 15 phút] phải là số thực.\n";
            sttThongBao++;
        }else if (TienIch.isStringFloat(txDiem15Phut.getText()) && !txDiem15Phut.getText().equals("")){
            if ((Float.parseFloat(txDiem15Phut.getText()) > 10) || (Float.parseFloat(txDiem15Phut.getText()) < 0)){
                dauVao = false;
                thongBao += sttThongBao + ". [Ô điểm 15 phút] hoặc bằng phải là số thực lớn hơn hoặc bằng 0 và bé hơn hoặc bằng 10.\n";
                sttThongBao++;
            }
        }
       

        if (!TienIch.isStringFloat(txDiem1Tiet.getText()) && !txDiem1Tiet.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". [Ô điểm 1 tiết] phải là số thực.\n";
            sttThongBao++;
        }else if (TienIch.isStringFloat(txDiem1Tiet.getText()) && !txDiem1Tiet.getText().equals("")){
            if ((Float.parseFloat(txDiem1Tiet.getText()) > 10) || (Float.parseFloat(txDiem1Tiet.getText()) < 0)){
                dauVao = false;
                thongBao += sttThongBao + ". [Ô điểm 1 tiết] phải là số thực lớn hơn hoặc bằng 0 và bé hơn hoặc bằng 10.\n";
                sttThongBao++;
            }
        }
        
        if (!TienIch.isStringFloat(txDiemThi.getText()) && !txDiemThi.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". [Ô điểm trung bình bằng] phải là số thực.\n";
            sttThongBao++;
        }else if (TienIch.isStringFloat(txDiemThi.getText()) && !txDiemThi.getText().equals("")){
            if ((Float.parseFloat(txDiemThi.getText()) > 10) || (Float.parseFloat(txDiemThi.getText()) < 0)){
                dauVao = false;
                thongBao += sttThongBao + ". [Ô điểm thi] hoặc bằng phải là số thực lớn hơn hoặc bằng 0 và bé hơn hoặc bằng 10.\n";
                sttThongBao++;
            }
        }
        
        if (!thongBao.equals("")) {
            JOptionPane.showMessageDialog(null, thongBao);
        }
        return dauVao;
    }
    
    private Boolean kiemTraDauVao() {
        String thongBao = "";
        int sttThongBao = 1;
        Boolean dauVao = true;
        
        if (!TienIch.isStringFloat(txDtbBeHon.getText()) && !txDtbBeHon.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". ]Ô điểm trung bình bé hơn] hoặc bằng phải là số thực.\n";
            sttThongBao++;
        }

        if (!TienIch.isStringFloat(txDtbLonHon.getText()) && !txDtbLonHon.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". ]Ô điểm trung bình lớn hơn] hoặc bằng phải là số thực.\n";
            sttThongBao++;
        }
        
        if (!TienIch.isStringFloat(txDtbBang.getText()) && !txDtbBang.getText().equals("")) {
            dauVao = false;
            thongBao += sttThongBao + ". [Ô điểm trung bình bằng] phải là số thực.\n";
            sttThongBao++;
        }
        
        if (!thongBao.equals("")) {
            JOptionPane.showMessageDialog(null, thongBao);
        }
        return dauVao;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgHk;
    private javax.swing.JButton btnChonLop;
    private javax.swing.JButton btnDocDanhSach;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTinhDtb;
    private javax.swing.JComboBox<String> cbxLopHoc;
    private javax.swing.JComboBox<String> cbxMonPhuTrach;
    private javax.swing.JComboBox<String> cbxNamHoc;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbDiem15Phut;
    private javax.swing.JLabel lbDiem1Tiet;
    private javax.swing.JLabel lbDiemTbLonHon;
    private javax.swing.JLabel lbDiemThi;
    private javax.swing.JLabel lbDtbBang;
    private javax.swing.JLabel lbDtbBeHon;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbHocKy;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbNamHoc;
    private javax.swing.JLabel lbSoKetQuaTimThay;
    private javax.swing.JLabel lbTen;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelInputDiem;
    private javax.swing.JRadioButton radHk1;
    private javax.swing.JRadioButton radHk2;
    private javax.swing.JScrollPane scrollPaneDiemChiTiet;
    private javax.swing.JScrollPane scrollPaneDiemTbMonTungHocSinh;
    private javax.swing.JTable tbDiemChiTiet;
    private javax.swing.JTable tbDiemTbMonTungHocSinh;
    private javax.swing.JTextField txDiem15Phut;
    private javax.swing.JTextField txDiem1Tiet;
    private javax.swing.JTextField txDiemThi;
    private javax.swing.JTextField txDtbBang;
    private javax.swing.JTextField txDtbBeHon;
    private javax.swing.JTextField txDtbLonHon;
    private javax.swing.JTextField txHo;
    private javax.swing.JTextField txMa;
    private javax.swing.JTextField txTen;
    // End of variables declaration//GEN-END:variables
}
