/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.DiemBUS;
import BusinessLogicLayer.DiemHocKiBUS;
import BusinessLogicLayer.HS_LopBUS;
import BusinessLogicLayer.LoaiDiemBUS;
import DataTransferObject.DiemDTO;
import DataTransferObject.HocSinhDTO;
import DataTransferObject.KetQuaHocTapHocKiDTO;
import DataTransferObject.LoaiDiemDTO;
import DataTransferObject.MonHocDTO;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mr932
 */
public class SubFrameDiemChiTietHocSinh extends javax.swing.JFrame {

    /**
     * Creates new form SubFrameDiemChiTietHocSinh
     */
    KetQuaHocTapHocKiDTO kqhthkCanShow;
    HS_LopBUS hslopBus;
    DiemBUS diemBus;
    LoaiDiemBUS ldBus;
    public SubFrameDiemChiTietHocSinh() {
        initComponents();
    }
    
    public SubFrameDiemChiTietHocSinh(KetQuaHocTapHocKiDTO kqhthkCanShow) {
        initComponents();
        hslopBus = new HS_LopBUS();
        diemBus = new DiemBUS();
        ldBus = new LoaiDiemBUS();
        
        String tenLop = hslopBus.timHocSinhLop(kqhthkCanShow.getHocSinh(), kqhthkCanShow.getHocKy(), kqhthkCanShow.getNamHoc()).getLop().getTenlop();
        this.kqhthkCanShow = kqhthkCanShow;
        lbThongTinMa.setText(kqhthkCanShow.getHocSinh().getMahs());
        lbThongTinHoTen.setText(kqhthkCanShow.getHocSinh().getHo() + " " + kqhthkCanShow.getHocSinh().getTen());
        lbThongTinHocKy.setText(kqhthkCanShow.getHocKy().getMahk());
        lbThongTinNamHoc.setText(kqhthkCanShow.getNamHoc().getTennh());
        lbThongTinDiemTrungBinh.setText(String.valueOf(kqhthkCanShow.getTbcHocky()));
        lbThongTinHanhKiem.setText(kqhthkCanShow.getHanhKiem());
        lbThongTinLop.setText(tenLop);
        String hinhHs = kqhthkCanShow.getHocSinh().getHinhAnh();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(hinhHs).getImage()
                .getScaledInstance(lbHinhAnh.getWidth(), lbHinhAnh.getHeight(), Image.SCALE_SMOOTH));
        lbHinhAnh.setText("");
        lbHinhAnh.setIcon(imageIcon);
        ArrayList<DiemDTO> dsDiemHocSinh = diemBus.timKiemDsDiemMotHocSinh(kqhthkCanShow.getHocSinh(), kqhthkCanShow.getHocKy(), kqhthkCanShow.getNamHoc());
        showTable(dsDiemHocSinh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        scrollPaneDiemChiTiet = new javax.swing.JScrollPane();
        tbDiemChiTiet = new javax.swing.JTable();
        panelInput = new javax.swing.JPanel();
        lbMa = new javax.swing.JLabel();
        lbThongTinMa = new javax.swing.JLabel();
        lbThongTinHocSinh = new javax.swing.JLabel();
        lbLop = new javax.swing.JLabel();
        lbHocKy = new javax.swing.JLabel();
        lbThongTinHocKy = new javax.swing.JLabel();
        lbDiemTrungBinh = new javax.swing.JLabel();
        lbThongTinDiemTrungBinh = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbThongTinHoTen = new javax.swing.JLabel();
        lbGvcn = new javax.swing.JLabel();
        lbThongTinGvcn = new javax.swing.JLabel();
        lbLop7 = new javax.swing.JLabel();
        lbThongTinNamHoc = new javax.swing.JLabel();
        lbHanhKiem = new javax.swing.JLabel();
        lbThongTinHanhKiem = new javax.swing.JLabel();
        lbHinhAnh = new javax.swing.JLabel();
        lbThongTinLop = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        lbHeader = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        scrollPaneDiemChiTiet.setToolTipText("");
        scrollPaneDiemChiTiet.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDiemChiTiet.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDiemChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên môn", "Điểm 15 phút", "Điểm 1 tiết", "Điểm thi học kỳ", "Điểm TB học kì"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDiemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDiemChiTiettbDSDSmouseClick(evt);
            }
        });
        scrollPaneDiemChiTiet.setViewportView(tbDiemChiTiet);

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        lbMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMa.setForeground(new java.awt.Color(23, 35, 51));
        lbMa.setText("Mã");

        lbThongTinMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinMa.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinMa.setText("thông tin");
        lbThongTinMa.setPreferredSize(new java.awt.Dimension(115, 13));

        lbThongTinHocSinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHocSinh.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHocSinh.setText("Thông tin học sinh");

        lbLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop.setForeground(new java.awt.Color(23, 35, 51));
        lbLop.setText("Lớp");

        lbHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbHocKy.setText("Học kỳ");

        lbThongTinHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHocKy.setText("thông tin");
        lbThongTinHocKy.setPreferredSize(new java.awt.Dimension(115, 13));

        lbDiemTrungBinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbDiemTrungBinh.setForeground(new java.awt.Color(23, 35, 51));
        lbDiemTrungBinh.setText("Điểm trung bình");

        lbThongTinDiemTrungBinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinDiemTrungBinh.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinDiemTrungBinh.setText("thông tin");
        lbThongTinDiemTrungBinh.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHoTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(23, 35, 51));
        lbHoTen.setText("Họ và tên");

        lbThongTinHoTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHoTen.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHoTen.setText("thông tin");
        lbThongTinHoTen.setPreferredSize(new java.awt.Dimension(115, 13));

        lbGvcn.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbGvcn.setForeground(new java.awt.Color(23, 35, 51));
        lbGvcn.setText("GVCN");

        lbThongTinGvcn.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinGvcn.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinGvcn.setText("thông tin");
        lbThongTinGvcn.setPreferredSize(new java.awt.Dimension(115, 13));

        lbLop7.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop7.setForeground(new java.awt.Color(23, 35, 51));
        lbLop7.setText("Năm học");

        lbThongTinNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinNamHoc.setText("thông tin");
        lbThongTinNamHoc.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHanhKiem.setForeground(new java.awt.Color(23, 35, 51));
        lbHanhKiem.setText("Hạnh kiểm");

        lbThongTinHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHanhKiem.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHanhKiem.setText("thông tin");
        lbThongTinHanhKiem.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHinhAnh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHinhAnh.setForeground(new java.awt.Color(23, 35, 51));
        lbHinhAnh.setText("Hình ảnh");

        lbThongTinLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinLop.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinLop.setText("thông tin");
        lbThongTinLop.setPreferredSize(new java.awt.Dimension(115, 13));

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLop)
                            .addComponent(lbDiemTrungBinh)
                            .addComponent(lbHocKy)
                            .addComponent(lbMa))
                        .addGap(34, 34, 34)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbThongTinDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHanhKiem)
                            .addComponent(lbLop7)
                            .addComponent(lbHoTen)
                            .addComponent(lbGvcn))
                        .addGap(33, 33, 33)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbThongTinHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinGvcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbThongTinHocSinh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46)
                .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbThongTinHocSinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(lbMa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbLop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbHocKy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDiemTrungBinh))
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelInputLayout.createSequentialGroup()
                                    .addComponent(lbThongTinHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThongTinGvcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThongTinNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThongTinHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelInputLayout.createSequentialGroup()
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbThongTinMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                                            .addComponent(lbThongTinHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbThongTinDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbGvcn)
                                                .addComponent(lbThongTinLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbLop7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbHanhKiem))))))))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        btnReport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnReport.setText("Report");

        lbHeader.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lbHeader.setText("Kết Quả Học Tập Học Kỳ");

        btnClose.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollPaneDiemChiTiet))))
                .addGap(64, 64, 64))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHeader)
                    .addComponent(btnClose))
                .addGap(34, 34, 34)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(scrollPaneDiemChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDiemChiTiettbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDiemChiTiettbDSDSmouseClick
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDiemChiTiettbDSDSmouseClick

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed
    
    private void showTable(ArrayList<DiemDTO> danhSachDiem){
        DiemHocKiBUS diemHkBus = new DiemHocKiBUS();
        Vector header = new Vector();
        header.add("STT");
        header.add("Môn");
        for (LoaiDiemDTO ld : ldBus.getDsld())
            header.add(ld.getTenLoaiDiem());
        header.add("Điểm TB Môn");
        DefaultTableModel model = new DefaultTableModel(header, 0);
        int stt = 1;
        MonHocDTO mh = null;
        Vector row = new Vector();
        for (DiemDTO diem : danhSachDiem){
            if (!diem.getMonHoc().equals(mh)){
                if (mh != null){
                    float dtbMon = diemHkBus.timDtbMonCuaHs(diem.getHocSinh(), mh, diem.getHocKy(), diem.getNamHoc());
                    row.add(dtbMon);
                    model.addRow(row);
                    stt++;
                }
                mh = diem.getMonHoc();
                System.out.println(mh.getTenmh());
                row = new Vector();
                row.add(stt);
                row.add(diem.getMonHoc().getTenmh());
            }
            row.add(diem.getDiemSo());
        }
        float dtbMon = diemHkBus.timDtbMonCuaHs(kqhthkCanShow.getHocSinh(), mh, kqhthkCanShow.getHocKy(), kqhthkCanShow.getNamHoc());
        row.add(dtbMon);
        model.addRow(row);
        tbDiemChiTiet.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubFrameDiemChiTietHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubFrameDiemChiTietHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubFrameDiemChiTietHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubFrameDiemChiTietHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubFrameDiemChiTietHocSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReport;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel lbDiemTrungBinh;
    private javax.swing.JLabel lbGvcn;
    private javax.swing.JLabel lbHanhKiem;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbHocKy;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbLop7;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbThongTinDiemTrungBinh;
    private javax.swing.JLabel lbThongTinGvcn;
    private javax.swing.JLabel lbThongTinHanhKiem;
    private javax.swing.JLabel lbThongTinHoTen;
    private javax.swing.JLabel lbThongTinHocKy;
    private javax.swing.JLabel lbThongTinHocSinh;
    private javax.swing.JLabel lbThongTinLop;
    private javax.swing.JLabel lbThongTinMa;
    private javax.swing.JLabel lbThongTinNamHoc;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JScrollPane scrollPaneDiemChiTiet;
    private javax.swing.JTable tbDiemChiTiet;
    // End of variables declaration//GEN-END:variables
}
