/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.LopBUS;
import BusinessLogicLayer.NamHocBUS;
import BusinessLogicLayer.PhongBUS;
import DataTransferObject.LopDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mr932
 */
public class SubFrameChonLop extends javax.swing.JFrame {

    /**
     * Creates new form SubFrameChonLop
     */
    JComboBox cbxChonLopChinh;
    LopBUS lopBus;
    NamHocBUS nhBus;
    PhongBUS phongBus;
    public SubFrameChonLop() {
        initComponents();
    }
    
    public SubFrameChonLop(JComboBox cbxChonLopChinh) {
        initComponents();
        this.cbxChonLopChinh = cbxChonLopChinh;
        lopBus = new LopBUS();
        nhBus = new NamHocBUS();
        phongBus = new PhongBUS();
        TienIch.duaGiaTriVaoCbx(cbxMaLop, lopBus.toStringList(lopBus.getDslop()));
        TienIch.duaGiaTriVaoCbx(cbxNamHoc, nhBus.toStringList(nhBus.getDsnh()));
        TienIch.duaGiaTriVaoCbx(cbxMaPhong, phongBus.toStringList(phongBus.getDsphong()));
        cbxMaLop.setSelectedItem(cbxChonLopChinh.getSelectedItem());
        if (!cbxMaLop.getSelectedItem().equals(""))
            showTable(lopBus.timKiemMalop((String) cbxMaLop.getSelectedItem()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        functionPanel = new javax.swing.JPanel();
        lbMaLop = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLop = new javax.swing.JTable();
        cbxMaLop = new javax.swing.JComboBox<>();
        lbTenLop = new javax.swing.JLabel();
        txTenLop = new javax.swing.JTextField();
        lbSiSo = new javax.swing.JLabel();
        txSiSo = new javax.swing.JTextField();
        lbNamHoc = new javax.swing.JLabel();
        lbTenPhong = new javax.swing.JLabel();
        lbMaGVCN = new javax.swing.JLabel();
        txMaGvcn = new javax.swing.JTextField();
        cbxNamHoc = new javax.swing.JComboBox<>();
        cbxMaPhong = new javax.swing.JComboBox<>();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbHeader.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lbHeader.setText("Thông Tin Lớp");

        functionPanel.setBackground(new java.awt.Color(255, 255, 255));
        functionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        lbMaLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMaLop.setText("Mã Lớp");

        btnTim.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnChon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnDoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDoc.setText("Đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        tbLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Tên lớp", "Sỉ số", "Mã GVCN", "Họ và Tên GVCN", "Năm Học", "Mã phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLopMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbLop);

        cbxMaLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxMaLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbTenLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTenLop.setText("Tên lớp");

        txTenLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txTenLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTenLopActionPerformed(evt);
            }
        });

        lbSiSo.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbSiSo.setText("Sỉ số");

        txSiSo.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N

        lbNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc.setText("Năm học");

        lbTenPhong.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTenPhong.setText("Mã phòng");

        lbMaGVCN.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMaGVCN.setText("Mã GVCN");

        txMaGvcn.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        txMaGvcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMaGvcnActionPerformed(evt);
            }
        });

        cbxNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxMaPhong.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxMaPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbNamHoc)
                                .addComponent(lbTenLop)
                                .addComponent(lbSiSo))
                            .addComponent(lbMaLop))
                        .addGap(40, 40, 40)
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(functionPanelLayout.createSequentialGroup()
                                .addComponent(cbxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)
                                .addComponent(btnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnChon))
                            .addGroup(functionPanelLayout.createSequentialGroup()
                                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txTenLop)
                                        .addComponent(txSiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(functionPanelLayout.createSequentialGroup()
                                        .addComponent(lbTenPhong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(functionPanelLayout.createSequentialGroup()
                                        .addComponent(lbMaGVCN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txMaGvcn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(114, 114, 114)))
                        .addGap(11, 11, 11)))
                .addGap(27, 27, 27))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaLop)
                    .addComponent(btnChon)
                    .addComponent(btnDoc)
                    .addComponent(btnTim)
                    .addComponent(cbxMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenLop)
                    .addComponent(txTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSiSo)
                            .addComponent(txSiSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNamHoc)
                            .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaGVCN)
                            .addComponent(txMaGvcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenPhong)
                            .addComponent(cbxMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        btnThoat.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnThoat.setText("X");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(functionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHeader)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(functionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        cbxChonLopChinh.setSelectedItem(cbxMaLop.getSelectedItem());
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        if (lopBus.getDslop() != null)
            showTable(lopBus.getDslop());
        else
            JOptionPane.showMessageDialog(null, "Không tìm thấy danh sách lớp.");
    }//GEN-LAST:event_btnDocActionPerformed

    private void tbLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLopMouseClicked
        // TODO add your handling code here:
        chonLop();
    }//GEN-LAST:event_tbLopMouseClicked

    private void txTenLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTenLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTenLopActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txMaGvcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMaGvcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMaGvcnActionPerformed
    
    private void timKiem(){
        ArrayList<LopDTO> danhSachLopTimThay= lopBus.getDslop();
        
        String maCanTim = (String) cbxMaLop.getSelectedItem();
        String tenLopCanTim = TienIch.chuanHoa(txTenLop.getText());
        String namHoc = (String) cbxNamHoc.getSelectedItem();
        String thongTinPhong = (String) cbxMaPhong.getSelectedItem();
        String siSo = txSiSo.getText();
        String maGv = txMaGvcn.getText();
        
        if (!maCanTim.equals(""))
            danhSachLopTimThay = lopBus.timKiemTheoMa(maCanTim, danhSachLopTimThay);
        
        
        if (!tenLopCanTim.equals(""))
            danhSachLopTimThay = lopBus.timKiemTheoTenLop(tenLopCanTim, danhSachLopTimThay);
        
        
        if (!namHoc.equals(""))
            danhSachLopTimThay = lopBus.timKiemTheoNamHoc(namHoc, danhSachLopTimThay);
        
        if (!thongTinPhong.equals(""))
            danhSachLopTimThay = lopBus.timKiemTheoPhong(thongTinPhong, danhSachLopTimThay);
        
        if (!maGv.equals(""))
            danhSachLopTimThay = lopBus.timKiemTheoGVCN(maGv, danhSachLopTimThay);
        
        if (!siSo.equals(""))
            danhSachLopTimThay = lopBus.timKiemSiSoBeHon(Integer.parseInt(siSo), danhSachLopTimThay);
        
        showTable(danhSachLopTimThay);
    }
    
    private void chonLop(){
        int row = tbLop.getSelectedRow();
        if (row >= 0){
            String maLop = (String) tbLop.getModel().getValueAt(row, 0);
            String tenLop = (String) tbLop.getModel().getValueAt(row, 1);
            String siSo = String.valueOf(tbLop.getModel().getValueAt(row, 2)) ;
            String maGv = (String) tbLop.getModel().getValueAt(row, 3);
            String namHoc = (String) tbLop.getModel().getValueAt(row, 5);
            String maPhong = (String) tbLop.getModel().getValueAt(row, 6);
            
            cbxMaLop.setSelectedItem(maLop);
            txTenLop.setText(tenLop);
            txSiSo.setText(siSo);
            txMaGvcn.setText(maGv);
            cbxNamHoc.setSelectedItem(namHoc);
            cbxMaPhong.setSelectedItem(maPhong);
        }
    }
    
    private void showTable(ArrayList<LopDTO> dsl){
        Vector header = new Vector();
        header.add("Mã lớp");
        header.add("Tên lớp");
        header.add("Sỉ số");
        header.add("Mã GVCN");
        header.add("Họ và tên GVCN");
        header.add("Năm học");
        header.add("Mã phòng");
        DefaultTableModel model = new DefaultTableModel(header, 0);
        for (LopDTO l : dsl) {
            Vector row = new Vector();
            row.add(l.getMalop());
            row.add(l.getTenlop());
            row.add(l.getSiso());
            row.add(l.getMaGVCN().getMagv());
            row.add(l.getMaGVCN().getHo() + " " + l.getMaGVCN().getTen());
            row.add(l.getManh().getManh());
            row.add(l.getMaphong().getMaphong());
            model.addRow(row);
        }
        tbLop.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubFrameChonLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubFrameChonLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubFrameChonLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubFrameChonLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubFrameChonLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbxMaLop;
    private javax.swing.JComboBox<String> cbxMaPhong;
    private javax.swing.JComboBox<String> cbxNamHoc;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbMaGVCN;
    private javax.swing.JLabel lbMaLop;
    private javax.swing.JLabel lbNamHoc;
    private javax.swing.JLabel lbSiSo;
    private javax.swing.JLabel lbTenLop;
    private javax.swing.JLabel lbTenPhong;
    private javax.swing.JTable tbLop;
    private javax.swing.JTextField txMaGvcn;
    private javax.swing.JTextField txSiSo;
    private javax.swing.JTextField txTenLop;
    // End of variables declaration//GEN-END:variables
}
