/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.DiemBUS;
import BusinessLogicLayer.HS_LopBUS;
import BusinessLogicLayer.HocBaCuoiNamBUS;
import BusinessLogicLayer.HocSinhBUS;
import BusinessLogicLayer.KetQuaHocTapHocKyBUS;
import BusinessLogicLayer.LoaiDiemBUS;
import BusinessLogicLayer.LopBUS;
import BusinessLogicLayer.NamHocBUS;
import DataTransferObject.DiemDTO;
import DataTransferObject.HocBaCuoiNamDTO;
import DataTransferObject.HocSinhDTO;
import DataTransferObject.KetQuaHocTapHocKiDTO;
import DataTransferObject.LopDTO;
import DataTransferObject.NamHocDTO;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mr932
 */
public class SubFrameHocBa extends javax.swing.JFrame {

    /**
     * Creates new form SubFrameHocBa
     */
    KetQuaHocTapHocKiDTO kqhthkCanShow;
    HS_LopBUS hslopBus;
    DiemBUS diemBus;
    LoaiDiemBUS ldBus;
    HocBaCuoiNamBUS hbcnBus;
    NamHocBUS nhBus;
    LopBUS lopBus;
    NamHocDTO nh;
    LopDTO lop;
    ArrayList<HocBaCuoiNamDTO> dshbLop;
    ArrayList<String> danhGia;
    public SubFrameHocBa() {
        initComponents();
    }
    
    public SubFrameHocBa(String maLopDuocChon, String maNh) {
        initComponents();
        hslopBus = new HS_LopBUS();
        diemBus = new DiemBUS();
        ldBus = new LoaiDiemBUS();
        hbcnBus = new HocBaCuoiNamBUS();
        nhBus = new NamHocBUS();
        lopBus = new LopBUS();
        dshbLop = new ArrayList<HocBaCuoiNamDTO>();
        danhGia = new ArrayList();
        danhGia.add("Tot");
        danhGia.add("Kha");
        danhGia.add("Trung Binh");
        danhGia.add("Yeu");
        for (HocBaCuoiNamDTO hbcn : hbcnBus.getDshbcn()){
            if (hslopBus.timHocSinhLop(hbcn.getHocSinh().getMahs(), "2", maNh) != null){
                String maLop = hslopBus.timHocSinhLop(hbcn.getHocSinh().getMahs(), "2", maNh).getLop().getMalop();
                if (maLop.equals(maLopDuocChon))
                    dshbLop.add(hbcn);
            }
        }
        nh = nhBus.timKiemNamHoc(maNh);
        lop = lopBus.timKiemMa(maLopDuocChon);
        TienIch.duaGiaTriVaoCbx(cbxHocLuc, danhGia);
        TienIch.duaGiaTriVaoCbx(cbxHanhKiem, danhGia);
        TienIch.duaGiaTriVaoCbx(cbxXepLoai, danhGia);
        showTable(dshbLop);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        scrollPaneDsHocBa = new javax.swing.JScrollPane();
        tbDsHocBa = new javax.swing.JTable();
        panelInput = new javax.swing.JPanel();
        lbMa = new javax.swing.JLabel();
        lbThongTinMa = new javax.swing.JLabel();
        lbThongTinHocSinh = new javax.swing.JLabel();
        lbLop = new javax.swing.JLabel();
        lbHocKy = new javax.swing.JLabel();
        lbThongTinDtb = new javax.swing.JLabel();
        lbHanhKiem = new javax.swing.JLabel();
        lbThongTinHanhKiem = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbThongTinHoTen = new javax.swing.JLabel();
        lbNamHoc = new javax.swing.JLabel();
        lbThongTinNamHoc = new javax.swing.JLabel();
        lbHocLuc = new javax.swing.JLabel();
        lbThongTinHocLuc = new javax.swing.JLabel();
        lbXepLoai = new javax.swing.JLabel();
        lbThongTinXepLoai = new javax.swing.JLabel();
        lbHinhAnh = new javax.swing.JLabel();
        lbThongTinLop = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        lbHeader = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        cbxHanhKiem = new javax.swing.JComboBox<>();
        cbxHocLuc = new javax.swing.JComboBox<>();
        cbxXepLoai = new javax.swing.JComboBox<>();
        lbTimKiemHanhKiem = new javax.swing.JLabel();
        lbTimKiemHocLuc = new javax.swing.JLabel();
        lbTimKiemXepLoai = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnDocDs = new javax.swing.JButton();
        lbSoKetQuaTimThay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPaneDsHocBa.setToolTipText("");
        scrollPaneDsHocBa.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbDsHocBa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbDsHocBa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ", "Tên", "Học lực", "Hạnh kiểm", "Xếp loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDsHocBa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDsHocBatbDSDSmouseClick(evt);
            }
        });
        scrollPaneDsHocBa.setViewportView(tbDsHocBa);

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        lbMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbMa.setForeground(new java.awt.Color(23, 35, 51));
        lbMa.setText("Mã");

        lbThongTinMa.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinMa.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinMa.setText("thông tin");
        lbThongTinMa.setPreferredSize(new java.awt.Dimension(115, 13));

        lbThongTinHocSinh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHocSinh.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHocSinh.setText("Thông tin học sinh");

        lbLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop.setForeground(new java.awt.Color(23, 35, 51));
        lbLop.setText("Lớp");

        lbHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbHocKy.setText("Điểm trung bình");

        lbThongTinDtb.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinDtb.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinDtb.setText("thông tin");
        lbThongTinDtb.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHanhKiem.setForeground(new java.awt.Color(23, 35, 51));
        lbHanhKiem.setText("Hạnh kiểm");

        lbThongTinHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHanhKiem.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHanhKiem.setText("thông tin");
        lbThongTinHanhKiem.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHoTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(23, 35, 51));
        lbHoTen.setText("Họ và tên");

        lbThongTinHoTen.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHoTen.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHoTen.setText("thông tin");
        lbThongTinHoTen.setPreferredSize(new java.awt.Dimension(115, 13));

        lbNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc.setText("Năm học");

        lbThongTinNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinNamHoc.setText("thông tin");
        lbThongTinNamHoc.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHocLuc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocLuc.setForeground(new java.awt.Color(23, 35, 51));
        lbHocLuc.setText("Học lực");

        lbThongTinHocLuc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinHocLuc.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinHocLuc.setText("thông tin");
        lbThongTinHocLuc.setPreferredSize(new java.awt.Dimension(115, 13));

        lbXepLoai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbXepLoai.setForeground(new java.awt.Color(23, 35, 51));
        lbXepLoai.setText("Xếp loại");

        lbThongTinXepLoai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinXepLoai.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinXepLoai.setText("thông tin");
        lbThongTinXepLoai.setPreferredSize(new java.awt.Dimension(115, 13));

        lbHinhAnh.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHinhAnh.setForeground(new java.awt.Color(23, 35, 51));
        lbHinhAnh.setText("Hình ảnh");

        lbThongTinLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbThongTinLop.setForeground(new java.awt.Color(23, 35, 51));
        lbThongTinLop.setText("thông tin");
        lbThongTinLop.setPreferredSize(new java.awt.Dimension(115, 13));

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLop)
                            .addComponent(lbHanhKiem)
                            .addComponent(lbHocKy)
                            .addComponent(lbMa))
                        .addGap(34, 34, 34)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbThongTinHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinDtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbXepLoai)
                            .addComponent(lbHocLuc)
                            .addComponent(lbHoTen)
                            .addComponent(lbNamHoc))
                        .addGap(33, 33, 33)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbThongTinXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThongTinNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbThongTinHocSinh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46)
                .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbThongTinHocSinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(lbMa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbLop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbHocKy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbHanhKiem))
                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelInputLayout.createSequentialGroup()
                                    .addComponent(lbThongTinHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThongTinNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThongTinHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbThongTinXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelInputLayout.createSequentialGroup()
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbThongTinMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                                            .addComponent(lbThongTinDtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbThongTinHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                                            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbNamHoc)
                                                .addComponent(lbThongTinLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbHocLuc)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbXepLoai))))))))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        btnReport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnReport.setText("Report");

        lbHeader.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lbHeader.setText("Học bạ cuối năm");

        btnClose.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        cbxHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxHanhKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxHocLuc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxHocLuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxXepLoai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxXepLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbTimKiemHanhKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTimKiemHanhKiem.setForeground(new java.awt.Color(23, 35, 51));
        lbTimKiemHanhKiem.setText("Hạnh kiểm");

        lbTimKiemHocLuc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTimKiemHocLuc.setForeground(new java.awt.Color(23, 35, 51));
        lbTimKiemHocLuc.setText("Học lực");

        lbTimKiemXepLoai.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTimKiemXepLoai.setForeground(new java.awt.Color(23, 35, 51));
        lbTimKiemXepLoai.setText("Xếp loại");

        btnTimKiem.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnDocDs.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDocDs.setText("Đọc DS");
        btnDocDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDsActionPerformed(evt);
            }
        });

        lbSoKetQuaTimThay.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbSoKetQuaTimThay.setText("Số kết quả tìm thấy");

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lbSoKetQuaTimThay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDocDs)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollPaneDsHocBa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, functionPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lbTimKiemHanhKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTimKiemHocLuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTimKiemXepLoai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHeader)
                    .addComponent(btnClose))
                .addGap(34, 34, 34)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHanhKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTimKiemHanhKiem)
                    .addComponent(lbTimKiemHocLuc)
                    .addComponent(lbTimKiemXepLoai)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneDsHocBa, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReport)
                    .addComponent(btnDocDs)
                    .addComponent(lbSoKetQuaTimThay))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDsHocBatbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDsHocBatbDSDSmouseClick
        // TODO add your handling code here:
        int row = tbDsHocBa.getSelectedRow();
        if (row >= 0){
            HocSinhBUS hsBus = new HocSinhBUS();
            HocSinhDTO hs = hsBus.timKiemHocSinh((String) tbDsHocBa.getModel().getValueAt(row, 1));
            lbThongTinMa.setText(hs.getMahs());
            lbThongTinHoTen.setText(hs.getHo() + " " + hs.getTen());
            lbThongTinDtb.setText(String.valueOf(tbDsHocBa.getModel().getValueAt(row, 4)));
            lbThongTinHocLuc.setText((String) tbDsHocBa.getModel().getValueAt(row, 5));
            lbThongTinHanhKiem.setText((String) tbDsHocBa.getModel().getValueAt(row, 6));
            lbThongTinXepLoai.setText((String) tbDsHocBa.getModel().getValueAt(row, 7));
            lbThongTinLop.setText(lop.getTenlop());
            lbThongTinNamHoc.setText(nh.getTennh());
            String hinhHs = hs.getHinhAnh();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(hinhHs).getImage()
                .getScaledInstance(lbHinhAnh.getWidth(), lbHinhAnh.getHeight(), Image.SCALE_SMOOTH));
            lbHinhAnh.setText("");
            lbHinhAnh.setIcon(imageIcon);
        }
    }//GEN-LAST:event_tbDsHocBatbDSDSmouseClick

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDocDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDsActionPerformed
        // TODO add your handling code here:
        doc();
    }//GEN-LAST:event_btnDocDsActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed
    
    private void timKiem(){
        ArrayList<HocBaCuoiNamDTO> dskq = dshbLop;
        String hocLuc = (String) cbxHocLuc.getSelectedItem();
        String hanhKiem = (String) cbxHanhKiem.getSelectedItem();
        String xepLoai = (String) cbxXepLoai.getSelectedItem();
        
        if (!hanhKiem.equals(""))
                dskq = hbcnBus.timKiemHanhKiem(hanhKiem, dskq);
        
        if (!hocLuc.equals(""))
                dskq = hbcnBus.timKiemHocLuc(hocLuc, dskq);
        
        if (!xepLoai.equals(""))
                dskq = hbcnBus.timKiemXepLoai(xepLoai, dskq);
        
        showTable(dskq);
        
    }
    
    private void doc(){
        if (dshbLop != null)
            showTable(dshbLop);
        else
            JOptionPane.showMessageDialog(null, "Không tìm thấy học sinh nào.");
    }
    
    private void showTable(ArrayList<HocBaCuoiNamDTO> dsHb){
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã");
        header.add("Họ");
        header.add("Tên");
        header.add("Đtb cả năm");
        header.add("Học lực");
        header.add("Hạnh kiểm");
        header.add("Xếp loại");
        int stt = 1;
        DefaultTableModel model = new DefaultTableModel(header, 0);
        for (HocBaCuoiNamDTO hbcn : dsHb){
            Vector row = new Vector();
            row.add(stt);
            row.add(hbcn.getHocSinh().getMahs());
            row.add(hbcn.getHocSinh().getHo());
            row.add(hbcn.getHocSinh().getTen());
            row.add(hbcn.getDtbCn());
            row.add(hbcn.getHocLuc());
            row.add(hbcn.getHanhKiem());
            row.add(hbcn.getXepLoai());
            model.addRow(row);
            stt++;
        }
        tbDsHocBa.setModel(model);
        lbSoKetQuaTimThay.setText("Tìm thấy " + model.getRowCount() + " kết quả.");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubFrameHocBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubFrameHocBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubFrameHocBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubFrameHocBa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubFrameHocBa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDocDs;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxHanhKiem;
    private javax.swing.JComboBox<String> cbxHocLuc;
    private javax.swing.JComboBox<String> cbxXepLoai;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel lbHanhKiem;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbHocKy;
    private javax.swing.JLabel lbHocLuc;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbNamHoc;
    private javax.swing.JLabel lbSoKetQuaTimThay;
    private javax.swing.JLabel lbThongTinDtb;
    private javax.swing.JLabel lbThongTinHanhKiem;
    private javax.swing.JLabel lbThongTinHoTen;
    private javax.swing.JLabel lbThongTinHocLuc;
    private javax.swing.JLabel lbThongTinHocSinh;
    private javax.swing.JLabel lbThongTinLop;
    private javax.swing.JLabel lbThongTinMa;
    private javax.swing.JLabel lbThongTinNamHoc;
    private javax.swing.JLabel lbThongTinXepLoai;
    private javax.swing.JLabel lbTimKiemHanhKiem;
    private javax.swing.JLabel lbTimKiemHocLuc;
    private javax.swing.JLabel lbTimKiemXepLoai;
    private javax.swing.JLabel lbXepLoai;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JScrollPane scrollPaneDsHocBa;
    private javax.swing.JTable tbDsHocBa;
    // End of variables declaration//GEN-END:variables
}
