/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author mr932
 */
public class SubMenuDiem extends javax.swing.JFrame {

    /**
     * Creates new form SubMenuDiem
     */
    JPanel funPanel;
    JInternalFrame diemToanTruongGUI;
    JInternalFrame diemBoMonGUI;
    JInternalFrame diemLopGUI;
    public SubMenuDiem() {
        initComponents();
    }
    
    public SubMenuDiem(JPanel funPanel, JInternalFrame diemToanTruongGUI, JInternalFrame diemBoMonGUI, JInternalFrame diemLopGUI) {
        initComponents();
        this.diemToanTruongGUI = diemToanTruongGUI;
        this.diemBoMonGUI = diemBoMonGUI;
        this.diemLopGUI = diemLopGUI;
        this.funPanel = funPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDiemToanTruong = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnDiemBoMon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnDiemLop = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        pnDiemToanTruong.setBackground(new java.awt.Color(23, 35, 51));
        pnDiemToanTruong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDiemToanTruongMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thống Kê Điểm Toàn Trường");

        javax.swing.GroupLayout pnDiemToanTruongLayout = new javax.swing.GroupLayout(pnDiemToanTruong);
        pnDiemToanTruong.setLayout(pnDiemToanTruongLayout);
        pnDiemToanTruongLayout.setHorizontalGroup(
            pnDiemToanTruongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiemToanTruongLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(37, 37, 37))
        );
        pnDiemToanTruongLayout.setVerticalGroup(
            pnDiemToanTruongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDiemToanTruongLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );

        pnDiemBoMon.setBackground(new java.awt.Color(23, 35, 51));
        pnDiemBoMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDiemBoMonMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quản Lý Điểm Bộ Môn");

        javax.swing.GroupLayout pnDiemBoMonLayout = new javax.swing.GroupLayout(pnDiemBoMon);
        pnDiemBoMon.setLayout(pnDiemBoMonLayout);
        pnDiemBoMonLayout.setHorizontalGroup(
            pnDiemBoMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemBoMonLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDiemBoMonLayout.setVerticalGroup(
            pnDiemBoMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemBoMonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnDiemLop.setBackground(new java.awt.Color(23, 35, 51));
        pnDiemLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDiemLopMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quản Lý Điểm Lớp");

        javax.swing.GroupLayout pnDiemLopLayout = new javax.swing.GroupLayout(pnDiemLop);
        pnDiemLop.setLayout(pnDiemLopLayout);
        pnDiemLopLayout.setHorizontalGroup(
            pnDiemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemLopLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDiemLopLayout.setVerticalGroup(
            pnDiemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiemLopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDiemToanTruong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDiemBoMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDiemLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnDiemToanTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnDiemBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnDiemLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnDiemToanTruongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDiemToanTruongMousePressed
        openJInternalFrame(diemToanTruongGUI);
    }//GEN-LAST:event_pnDiemToanTruongMousePressed

    private void pnDiemBoMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDiemBoMonMousePressed
        // TODO add your handling code here:
        openJInternalFrame(diemBoMonGUI);
    }//GEN-LAST:event_pnDiemBoMonMousePressed

    private void pnDiemLopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDiemLopMousePressed
        // TODO add your handling code here:
        openJInternalFrame(diemLopGUI);
    }//GEN-LAST:event_pnDiemLopMousePressed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited
    
    public void openJInternalFrame(JInternalFrame internalFrame){
        int height = funPanel.getHeight();
        int width = funPanel.getWidth();
        funPanel.removeAll();
        internalFrame.setSize(width, height);
        funPanel.add(internalFrame).setVisible(true);
        funPanel.repaint();
        funPanel.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMenuDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMenuDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMenuDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMenuDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMenuDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnDiemBoMon;
    private javax.swing.JPanel pnDiemLop;
    private javax.swing.JPanel pnDiemToanTruong;
    // End of variables declaration//GEN-END:variables
}
