/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicUserInterface;

import BusinessLogicLayer.GiaoVienBUS;
import BusinessLogicLayer.HocKyBUS;
import BusinessLogicLayer.LopBUS;
import BusinessLogicLayer.MonHocBUS;
import BusinessLogicLayer.NamHocBUS;
import BusinessLogicLayer.PhongBUS;
import BusinessLogicLayer.TKBBUS;
import DataTransferObject.LopDTO;
import DataTransferObject.NamHocDTO;
import DataTransferObject.TKBDTO;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author QuyenNguyen
 */
public class ThoiKhoaBieuGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThoiKhoaBieuGUI
     */
    TKBBUS tkbBus;
    ArrayList<String> thuNgay;
    public ThoiKhoaBieuGUI() throws Exception {
        initComponents();
        tkbBus = new TKBBUS();
        NamHocBUS nhBus = new NamHocBUS();
        nhBus.doc();
        MonHocBUS mhBus = new MonHocBUS();
        mhBus.docDSMH();
        GiaoVienBUS gvBus = new GiaoVienBUS();
        gvBus.docDSGV(mhBus.getDsmh());
        PhongBUS phongBus = new PhongBUS();
        phongBus.doc();
        LopBUS lopBus = new LopBUS();
        thuNgay = new ArrayList<>();
        thuNgay.add("Hai");
        thuNgay.add("Ba");
        thuNgay.add("Bon");
        thuNgay.add("Nam");
        thuNgay.add("Sau");
        lopBus.doc(nhBus.getDsnh(), gvBus.getDsgv(), phongBus.getDsphong());
        TienIch.duaGiaTriVaoCbx(cbxNamHoc, nhBus.toStringList(nhBus.getDsnh()));
        TienIch.duaGiaTriVaoCbx(cbxLop, lopBus.toStringList(lopBus.getDslop()));
        TienIch.duaGiaTriVaoCbx(cbxGiaoVien, gvBus.toStringList(gvBus.getDsgv()));
        TienIch.duaGiaTriVaoCbx(cbxThu, thuNgay);
        TienIch.duaGiaTriVaoCbx(cbxMon, mhBus.toStringList(mhBus.getDsmh()));
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        functionPanel = new javax.swing.JPanel();
        scrollPaneThoiKhoaBieu = new javax.swing.JScrollPane();
        tbThoiKhoaBieu = new javax.swing.JTable();
        btnReport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        panelInput = new javax.swing.JPanel();
        lbHocKy = new javax.swing.JLabel();
        lbNamHoc = new javax.swing.JLabel();
        cbxNamHoc = new javax.swing.JComboBox<>();
        radHk1 = new javax.swing.JRadioButton();
        radHk2 = new javax.swing.JRadioButton();
        btnDocDanhSach = new javax.swing.JButton();
        lbLop = new javax.swing.JLabel();
        cbxLop = new javax.swing.JComboBox<>();
        btnChonLop = new javax.swing.JButton();
        lbTietBD = new javax.swing.JLabel();
        lbTietKT = new javax.swing.JLabel();
        cbxTietBD = new javax.swing.JComboBox<>();
        cbxTietKT = new javax.swing.JComboBox<>();
        btTimKiemNangCao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbLop1 = new javax.swing.JLabel();
        cbxGiaoVien = new javax.swing.JComboBox<>();
        btnChonGv = new javax.swing.JButton();
        cbxMon = new javax.swing.JComboBox<>();
        btnChonMon = new javax.swing.JButton();
        cbxThu = new javax.swing.JComboBox<>();

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 35, 51));
        jLabel5.setText("Thời Khóa Biểu");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        scrollPaneThoiKhoaBieu.setToolTipText("");
        scrollPaneThoiKhoaBieu.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        tbThoiKhoaBieu.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        tbThoiKhoaBieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thứ", "Lớp", "Môn học", "Giáo Viên", "Tiết bắt đầu", "Tiết kết thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbThoiKhoaBieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThoiKhoaBieutbDSDSmouseClick(evt);
            }
        });
        scrollPaneThoiKhoaBieu.setViewportView(tbThoiKhoaBieu);

        btnReport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(scrollPaneThoiKhoaBieu)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addGap(110, 110, 110))
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scrollPaneThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReport)
                    .addComponent(btnExport))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInput.setBackground(new java.awt.Color(255, 255, 255));
        panelInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        panelInput.setForeground(new java.awt.Color(102, 102, 102));

        lbHocKy.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbHocKy.setForeground(new java.awt.Color(23, 35, 51));
        lbHocKy.setText("Học kỳ");

        lbNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbNamHoc.setForeground(new java.awt.Color(23, 35, 51));
        lbNamHoc.setText("Năm học");

        cbxNamHoc.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(radHk1);
        radHk1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk1.setText("1");

        buttonGroup1.add(radHk2);
        radHk2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        radHk2.setText("2");

        btnDocDanhSach.setBackground(new java.awt.Color(23, 35, 51));
        btnDocDanhSach.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnDocDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDocDanhSach.setText("Đọc Danh Sách");
        btnDocDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDanhSachActionPerformed(evt);
            }
        });

        lbLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop.setForeground(new java.awt.Color(23, 35, 51));
        lbLop.setText("Chọn lớp");

        cbxLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChonLop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnChonLop.setText("...");
        btnChonLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonLopActionPerformed(evt);
            }
        });

        lbTietBD.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTietBD.setForeground(new java.awt.Color(23, 35, 51));
        lbTietBD.setText("Tiết Bắt Đầu");

        lbTietKT.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbTietKT.setForeground(new java.awt.Color(23, 35, 51));
        lbTietKT.setText("Tiết Kết Thúc");

        cbxTietBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "null" }));

        cbxTietKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "null" }));

        btTimKiemNangCao.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btTimKiemNangCao.setText("Tìm kiếm");
        btTimKiemNangCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemNangCaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel1.setText("Thứ");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel2.setText("Môn");

        lbLop1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbLop1.setForeground(new java.awt.Color(23, 35, 51));
        lbLop1.setText("Chọn Giáo Viên");

        cbxGiaoVien.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxGiaoVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChonGv.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnChonGv.setText("...");
        btnChonGv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonGvActionPerformed(evt);
            }
        });

        cbxMon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChonMon.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        btnChonMon.setText("...");
        btnChonMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonMonActionPerformed(evt);
            }
        });

        cbxThu.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbxThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbxThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(310, 310, 310))
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(cbxMon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnChonMon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(lbTietBD)
                                .addGap(7, 7, 7)
                                .addComponent(cbxTietBD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbTietKT, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTietKT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNamHoc)
                            .addComponent(cbxNamHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addComponent(radHk1)
                                .addGap(8, 8, 8)
                                .addComponent(radHk2))
                            .addComponent(lbHocKy))
                        .addGap(30, 30, 30)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxLop, 0, 160, Short.MAX_VALUE)
                            .addComponent(lbLop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChonLop)
                        .addGap(24, 24, 24)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxGiaoVien, 0, 160, Short.MAX_VALUE)
                            .addComponent(lbLop1))
                        .addGap(18, 18, 18)
                        .addComponent(btnChonGv)
                        .addGap(33, 33, 33)))
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDocDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTimKiemNangCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNamHoc)
                            .addComponent(lbHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radHk1)
                            .addComponent(radHk2)
                            .addComponent(btnDocDanhSach)
                            .addComponent(btnChonLop)
                            .addComponent(cbxLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lbLop1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChonGv)
                            .addComponent(cbxGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btTimKiemNangCao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChonMon)
                            .addComponent(lbTietBD)
                            .addComponent(cbxTietBD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTietKT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTietKT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbThoiKhoaBieutbDSDSmouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThoiKhoaBieutbDSDSmouseClick
        // TODO add your handling code here:
        TKBBUS tkbBus = new TKBBUS();
        int row = tbThoiKhoaBieu.getSelectedRow();
        if (row >= 0) {
            cbxLop.setSelectedItem(tkbBus.timLopTheoTen(tbThoiKhoaBieu.getModel().getValueAt(row, 1).toString()));
        }
    }//GEN-LAST:event_tbThoiKhoaBieutbDSDSmouseClick

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        WritableWorkbook wordbook;
        try{
            
            wordbook = Workbook.createWorkbook(new File("thoikhoabieu.xls"));
            WritableSheet sheet=wordbook.createSheet("thoikhoabieu", 0);
            
            sheet.addCell(new Label(0,0,"Thứ"));
            sheet.addCell(new Label(1,0,"Lớp"));
            sheet.addCell(new Label(2,0,"Môn học"));
            sheet.addCell(new Label(3,0,"Giáo viên"));
            sheet.addCell(new Label(4,0,"Tiết bắt đầu"));
            sheet.addCell(new Label(5,0,"Tiết kết thúc"));
            int row=1;
            for(TKBDTO tkb: TKBBUS.dstkb){
                sheet.addCell(new Label(0,row,tkb.getThu()));
                sheet.addCell(new Label(1,row,tkb.getLop().getTenlop()));
                sheet.addCell(new Label(2,row,tkb.getMonHoc().getTenmh()));
                sheet.addCell(new Label(3,row,tkb.getGiaoVien().getTen()));
                sheet.addCell(new Label(4,row,Integer.toString(tkb.getTietBD())));
                sheet.addCell(new Label(5,row++,Integer.toString(tkb.getTietKT())));
            }
            
            wordbook.write();
            wordbook.close();
            JOptionPane.showMessageDialog(null,"Đã xuất thành công");
        } catch (IOException ex) {
            Logger.getLogger(ThoiKhoaBieuGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(ThoiKhoaBieuGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
        tkbBus.report();
        JOptionPane.showMessageDialog(null,"Đã report thành công");
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnChonLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonLopActionPerformed
        // TODO add your handling code here:
        SubFrameChonLop_TKB chonLop = new SubFrameChonLop_TKB(cbxLop.getSelectedItem().toString(),this);
        chonLop.setVisible(true);
    }//GEN-LAST:event_btnChonLopActionPerformed
    
    public void SetCbxLop(String maLop)
    {
        cbxLop.setSelectedItem(maLop);
    }
    
    private void btnDocDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDanhSachActionPerformed
        // TODO add your handling code here:
        
        showTable(tkbBus.getDstkb());
    }//GEN-LAST:event_btnDocDanhSachActionPerformed

    private void btTimKiemNangCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemNangCaoActionPerformed
        // TODO add your handling code here:
        //Tìm kiếm nâng cao
        ArrayList<TKBDTO> dstkb = tkbBus.getDstkb();
        String choose = null;
        if(radHk1.isSelected())
        choose = "1";
        if(radHk2.isSelected())
        choose = "2";
        String thongTinHocky = choose;
        String thongTinNamhoc = cbxNamHoc.getSelectedItem().toString();
        String thongTinLop = cbxLop.getSelectedItem().toString();
        String thongTinGV = cbxGiaoVien.getSelectedItem().toString();
        String thongTinMonhoc = cbxMon.getSelectedItem().toString();
        String thongTinThu = cbxThu.getSelectedItem().toString();
        String thongTinTietBD = cbxTietBD.getSelectedItem().toString();
        String thongTinTietKT = cbxTietKT.getSelectedItem().toString();
        
        if (!thongTinNamhoc.equals(""))
            dstkb = tkbBus.timKiemNamHoc(thongTinNamhoc, dstkb);
        
        if (!thongTinLop.equals(""))
            dstkb = tkbBus.timKiemLop(thongTinLop, dstkb);
        
        if (!thongTinGV.equals(""))
            dstkb = tkbBus.timKiemGV(thongTinGV, dstkb);
        
        if (!thongTinMonhoc.equals(""))
            dstkb = tkbBus.timKiemMonHoc(thongTinMonhoc, dstkb);
        
        if (!thongTinThu.equals(""))
            dstkb = tkbBus.timKiemThu(thongTinThu, dstkb);
        
        if (!thongTinTietBD.equals(""))
            dstkb = tkbBus.timKiemTietBD(thongTinTietBD, dstkb);
        
        if (!thongTinTietKT.equals(""))
            dstkb = tkbBus.timKiemTietKT(thongTinTietKT, dstkb);
        
        showTable(dstkb);
        
    }//GEN-LAST:event_btTimKiemNangCaoActionPerformed

    private void btnChonGvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonGvActionPerformed
        // TODO add your handling code here:
        SubFrameChonGV chonGiaoVien = new SubFrameChonGV(cbxGiaoVien);
        chonGiaoVien.setSize(767, 462);
        chonGiaoVien.setVisible(true);
    }//GEN-LAST:event_btnChonGvActionPerformed

    private void btnChonMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMonActionPerformed
        // TODO add your handling code here:
        SubFrameChonMon frameChonMon = new SubFrameChonMon(cbxMon);
        frameChonMon.setSize(767, 462);
        frameChonMon.setVisible(true);
    }//GEN-LAST:event_btnChonMonActionPerformed

    private void cbxThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxThuActionPerformed

    /*
    private String chuanHoa(String chuoiDauVao) {
        chuoiDauVao= chuanHoa(chuoiDauVao);
        String temp[] = chuoiDauVao.split(" ");
        chuoiDauVao = ""; 
        for (int i = 0; i < temp.length; i++) {
            chuoiDauVao += String.valueOf(temp[i].charAt(0)).toUpperCase() + temp[i].substring(1);
            if (i < temp.length - 1) //
                chuoiDauVao += " ";
        }
        return chuoiDauVao;
    }
    */
    private String chuanHoa(String chuoiDauVao) {
        String chuoiBoKhoangTrang = chuoiDauVao.trim();
        String[] arr = chuoiBoKhoangTrang.split(" ");
        StringBuffer sb = new StringBuffer();

        for (int i = 0; i < arr.length; i++) {
            //System.out.println(arr[i]);
            if (arr[i].equals("")) {
                continue;
            }
            //if (!arr[i].equals("")){
            //System.out.println(arr[i]);
            sb.append(Character.toUpperCase(arr[i].charAt(0))).append(arr[i].substring(1)).append(" ");
            //}
        }
        return sb.toString().trim();
    }
    
    private void showTable(ArrayList<TKBDTO> dstkb){
        Vector header = new Vector();
        header.add("Thứ");
        header.add("Lớp");
        header.add("Môn học");
        header.add("Mã Giáo viên");
        header.add("Họ và tên Giáo viên");
        header.add("Tiết bắt đầu");
        header.add("Tiết kết thúc");
        DefaultTableModel model = new DefaultTableModel(header, 0);
        for (TKBDTO tkb : dstkb) {
            Vector row = new Vector();
            row.add(tkb.getThu());
            row.add(tkb.getLop().getTenlop());
            row.add(tkb.getMonHoc().getTenmh());
            row.add(tkb.getGiaoVien().getMagv());
            row.add(tkb.getGiaoVien().getHo() + " " + tkb.getGiaoVien().getTen());
            row.add(tkb.getTietBD());
            row.add(tkb.getTietKT());
            model.addRow(row);
        }
        tbThoiKhoaBieu.setModel(model);
    }
    private void show(ArrayList<TKBDTO> dskq){
        Vector header = new Vector();
        header.add("Thứ");
        header.add("Lớp");
        header.add("Môn học");
        header.add("Giáo viên");
        header.add("Tiết bắt đầu");
        header.add("Tiết kết thúc");
        DefaultTableModel model = new DefaultTableModel(header, 0);
        TKBBUS tkbBus = new TKBBUS();
        for(TKBDTO tkb:dskq){
            Vector row = new Vector();
            row.add(tkb.getThu());
            row.add(tkb.getLop().getTenlop());
            row.add(tkb.getMonHoc().getTenmh());
            row.add(tkb.getGiaoVien().getTen());
            row.add(tkb.getTietBD());
            row.add(tkb.getTietKT());
            model.addRow(row);
        }
        tbThoiKhoaBieu.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTimKiemNangCao;
    private javax.swing.JButton btnChonGv;
    private javax.swing.JButton btnChonLop;
    private javax.swing.JButton btnChonMon;
    private javax.swing.JButton btnDocDanhSach;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnReport;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxGiaoVien;
    private javax.swing.JComboBox<String> cbxLop;
    private javax.swing.JComboBox<String> cbxMon;
    private javax.swing.JComboBox<String> cbxNamHoc;
    private javax.swing.JComboBox<String> cbxThu;
    private javax.swing.JComboBox<String> cbxTietBD;
    private javax.swing.JComboBox<String> cbxTietKT;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbHocKy;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbLop1;
    private javax.swing.JLabel lbNamHoc;
    private javax.swing.JLabel lbTietBD;
    private javax.swing.JLabel lbTietKT;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInput;
    private javax.swing.JRadioButton radHk1;
    private javax.swing.JRadioButton radHk2;
    private javax.swing.JScrollPane scrollPaneThoiKhoaBieu;
    private javax.swing.JTable tbThoiKhoaBieu;
    // End of variables declaration//GEN-END:variables

    
}
